#!/usr/bin/env python3
"""
engines/D_Publish.py — Frontend Asset Publisher

Single point of contact between the canonical data store (data/) and the
frontend cache (html/data/).  No other engine should write to html/data/
(except progress JSONs written live during execution).

Responsibilities:
  1. Symlink canonical CSVs/JSONs from data/ → html/data/
  2. Generate derived "latest" JSON snapshots from historical CSVs
  3. Generate pipeline_latest.json (model projected onto real portfolio value)
  4. Generate scored_targets.json
  5. Generate MIS JSONs (model + real)

Usage:
    python3 engines/D_Publish.py
"""

# --- Script Version ---
D_PUBLISH_VERSION = "1.3.0"

import csv
import json
import math
import os
import sys
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

# Ensure project root is on sys.path
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

# ═══════════════════════════════════════════════════════════════════════════════
# PATHS — Canonical sources (data/) and targets (html/data/)
# ═══════════════════════════════════════════════════════════════════════════════

SRC = ROOT / "data"
DST = ROOT / "html" / "data"

# --- Canonical source files ---
FINDB_DIR = SRC / "findb"
STOCK_DATA_DB = FINDB_DIR / "StockDataDB.csv"
FINANCIALS_DB = FINDB_DIR / "FinancialsDB.csv"

RESULTS_DIR = SRC / "results"
SCORED_STOCKS_CSV = RESULTS_DIR / "scored_stocks.csv"
SECTOR_PE_CSV = RESULTS_DIR / "sector_pe.csv"
CORRELATION_MATRIX_CSV = RESULTS_DIR / "correlation_matrix.csv"
PORTFOLIO_RESULTS_CSV = RESULTS_DIR / "portfolio_results_db.csv"
GA_FITNESS_CSV = RESULTS_DIR / "ga_fitness_noise_db.csv"
OPTIMIZED_HISTORY_CSV = RESULTS_DIR / "optimized_portfolio_history.csv"
DIAGNOSTICS_HISTORY_CSV = RESULTS_DIR / "portfolio_diagnostics_history.csv"
ATTRIBUTION_HISTORY_CSV = RESULTS_DIR / "performance_attribution_history.csv"
ASSET_ATTRIBUTION_CSV = RESULTS_DIR / "asset_attribution_history.csv"
PERF_WINDOWS_CSV = RESULTS_DIR / "performance_windows_history.csv"
SCORING_PERF_CSV = RESULTS_DIR / "scoring_performance.csv"
PORTFOLIO_PERF_CSV = RESULTS_DIR / "portfolio_performance.csv"
DOWNLOAD_PERF_CSV = RESULTS_DIR / "download_performance.csv"

LEDGER_CSV = SRC / "ledger.csv"
LATEST_RUN_SUMMARY_JSON = RESULTS_DIR / "latest_run_summary.json"
OPTIMIZED_RECOMMENDATION_JSON = RESULTS_DIR / "optimized_recommendation.json"
LEDGER_POSITIONS_JSON = SRC / "ledger_positions.json"
PORTFOLIO_HISTORY_JSON = SRC / "portfolio_history.json"
PORTFOLIO_TIMESERIES_CSV = RESULTS_DIR / "portfolio_timeseries.csv"
DIAGNOSTICS_JSON = RESULTS_DIR / "portfolio_diagnostics.json"
ATTRIBUTION_JSON = RESULTS_DIR / "performance_attribution.json"

TICKERS_FILE = ROOT / "parameters" / "tickers.txt"

# --- Derived files (generated by D_Publish, stored in data/results/) ---
DERIVED_DIR = RESULTS_DIR
SCORED_TARGETS_JSON = DERIVED_DIR / "scored_targets.json"
PIPELINE_LATEST_JSON = DERIVED_DIR / "pipeline_latest.json"
MIS_MODEL_LATEST_JSON = DERIVED_DIR / "mis_model_latest.json"
MIS_REAL_LATEST_JSON = DERIVED_DIR / "mis_real_latest.json"

# --- Progress files (written live by engines, canonical in data/) ---
PROGRESS_DIR = SRC
PROGRESS_FILES = [
    "pipeline_progress.json",
    "download_progress.json",
    "scoring_progress.json",
    "portfolio_progress.json",
]

# Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - D_Publish - %(levelname)s - %(message)s",
)
logger = logging.getLogger("D_Publish")


# ═══════════════════════════════════════════════════════════════════════════════
# UTILITIES
# ═══════════════════════════════════════════════════════════════════════════════


def safe_float(v: Any, default: float = 0.0) -> float:
    """Safely convert a value to float."""
    if v is None or v == "":
        return default
    try:
        return float(v)
    except (TypeError, ValueError):
        return default


def sanitize_for_json(value: Any) -> Any:
    """Replace NaN/Inf with None for JSON serialization."""
    if isinstance(value, dict):
        return {k: sanitize_for_json(v) for k, v in value.items()}
    if isinstance(value, list):
        return [sanitize_for_json(v) for v in value]
    if isinstance(value, float):
        if not math.isfinite(value):
            return None
    return value


def write_json(path: Path, payload: dict) -> None:
    """Write JSON with NaN sanitization."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(sanitize_for_json(payload), f, indent=2, ensure_ascii=False, allow_nan=False)
    logger.info(f"  Wrote {path.name}")


def ensure_symlink(src: Path, dst_dir: Path, dst_name: Optional[str] = None) -> bool:
    """Create a symlink in dst_dir pointing to src.  Returns True on success.

    If the destination already exists:
      - If it's a symlink pointing to src → no-op
      - If it's a symlink pointing elsewhere → replace
      - If it's a regular file → remove and replace with symlink
    Uses *absolute* paths so the link works regardless of cwd.
    """
    if not src.exists():
        logger.warning(f"  Source not found, skipping: {src.name}")
        return False

    src_abs = src.resolve()
    dst = dst_dir / (dst_name or src.name)
    dst.parent.mkdir(parents=True, exist_ok=True)

    # Already a correct symlink?
    if dst.is_symlink():
        try:
            if dst.resolve() == src_abs:
                logger.info(f"  {dst.name} ✓ symlink OK")
                return True
        except OSError:
            pass
        # Wrong target — remove and recreate
        dst.unlink()

    # Regular file occupying the slot — remove it
    if dst.exists():
        dst.unlink()

    os.symlink(src_abs, dst)
    logger.info(f"  {dst.name} → {src_abs}")
    return True


def read_json_safe(path: Path) -> dict:
    """Read a JSON file, returning empty dict if missing or corrupt."""
    if not path.exists():
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        logger.warning(f"  Could not read {path.name}: {e}")
        return {}


def latest_csv_rows(path: Path, run_id_col: str = "run_id") -> pd.DataFrame:
    """Read a CSV and return only rows from the latest run_id."""
    if not path.exists():
        return pd.DataFrame()
    try:
        df = pd.read_csv(path)
        if run_id_col not in df.columns or df.empty:
            return df
        latest = df[run_id_col].max()
        return df[df[run_id_col] == latest].copy()
    except Exception as e:
        logger.warning(f"  Could not read {path.name}: {e}")
        return pd.DataFrame()


def normalize_ticker(s: Optional[str]) -> str:
    """Normalize string for ticker matching (uppercase, alphanum only)."""
    if not s:
        return ""
    return "".join(c for c in str(s).upper() if c.isalnum())


def resolve_source(canonical: Path, fallback_name: Optional[str] = None) -> Path:
    """Return canonical path if it exists, otherwise fall back to html/data/.

    During the transition period some files may only exist in html/data/ because
    the pipeline hasn't been fully re-run yet.  This helper transparently picks
    whichever copy is available (preferring canonical).
    """
    if canonical.exists():
        return canonical
    fb = DST / (fallback_name or canonical.name)
    if fb.exists():
        logger.debug(f"  Fallback: using {fb} (canonical {canonical} not yet created)")
        return fb
    return canonical  # caller will handle missing file


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 0: GENERATE DERIVED SNAPSHOT JSONs FROM HISTORY CSVs
# ═══════════════════════════════════════════════════════════════════════════════


def publish_derived_snapshots() -> None:
    """Generate snapshot JSONs from the latest row of their history CSVs.

    These files used to be written directly by A4_Analysis.py.  Now A4 only
    appends to the history CSVs and D_Publish derives the snapshot JSONs,
    eliminating the duplication.

    Generated files (in data/results/):
      - portfolio_diagnostics.json   ← from portfolio_diagnostics_history.csv
      - performance_attribution.json ← from performance_attribution_history.csv
    """
    logger.info("Step 0: Generating derived snapshot JSONs from history CSVs")

    # --- portfolio_diagnostics.json ---
    diag = latest_csv_rows(DIAGNOSTICS_HISTORY_CSV)
    if not diag.empty:
        row = diag.iloc[0]
        payload = {k: (None if pd.isna(v) else v) for k, v in row.to_dict().items()}
        write_json(DIAGNOSTICS_JSON, payload)
        ensure_symlink(DIAGNOSTICS_JSON, DST)
    else:
        logger.warning("  No diagnostics history data — skipping portfolio_diagnostics.json")

    # --- performance_attribution.json ---
    attr = latest_csv_rows(ATTRIBUTION_HISTORY_CSV)
    if not attr.empty:
        row = attr.iloc[0]
        payload = {k: (None if pd.isna(v) else v) for k, v in row.to_dict().items()}
        write_json(ATTRIBUTION_JSON, payload)
        ensure_symlink(ATTRIBUTION_JSON, DST)
    else:
        logger.warning("  No attribution history data — skipping performance_attribution.json")


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 1: COPY CANONICAL FILES
# ═══════════════════════════════════════════════════════════════════════════════


def publish_symlink_files() -> None:
    """Create symlinks in html/data/ pointing to canonical files in data/."""
    logger.info("Step 1: Symlinking canonical files to html/data/")

    # CSVs from data/results/
    ensure_symlink(SCORED_STOCKS_CSV, DST)
    ensure_symlink(SECTOR_PE_CSV, DST)
    ensure_symlink(CORRELATION_MATRIX_CSV, DST)
    ensure_symlink(PORTFOLIO_RESULTS_CSV, DST)  # also exposed as mis_model_history.csv (Step 4)
    ensure_symlink(GA_FITNESS_CSV, DST)
    ensure_symlink(SCORING_PERF_CSV, DST)
    ensure_symlink(PORTFOLIO_PERF_CSV, DST)
    ensure_symlink(DOWNLOAD_PERF_CSV, DST)

    # StockDataDB
    ensure_symlink(STOCK_DATA_DB, DST)

    # Ledger CSV
    ensure_symlink(LEDGER_CSV, DST)

    # Tickers file
    ensure_symlink(TICKERS_FILE, DST)

    # JSONs — use resolve_source to fallback to html/data/ during transition
    # Note: DIAGNOSTICS_JSON and ATTRIBUTION_JSON are generated by
    # publish_derived_snapshots() and symlinked there.
    for json_src in [LATEST_RUN_SUMMARY_JSON, OPTIMIZED_RECOMMENDATION_JSON,
                     LEDGER_POSITIONS_JSON, PORTFOLIO_HISTORY_JSON]:
        resolved = resolve_source(json_src)
        # Only symlink if the resolved source is outside html/data/
        if resolved.parent != DST:
            ensure_symlink(resolved, DST, json_src.name)

    # Portfolio timeseries
    resolved_ts = resolve_source(PORTFOLIO_TIMESERIES_CSV)
    if resolved_ts.parent != DST:
        ensure_symlink(resolved_ts, DST, PORTFOLIO_TIMESERIES_CSV.name)


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 2: GENERATE SCORED_TARGETS.JSON
# ═══════════════════════════════════════════════════════════════════════════════


def publish_scored_targets() -> Dict[str, float]:
    """Generate scored_targets.json from latest scored_stocks.csv run."""
    logger.info("Step 2: Generating scored_targets.json")

    targets: Dict[str, float] = {}
    symbols: Dict[str, str] = {}

    latest = latest_csv_rows(SCORED_STOCKS_CSV)
    if latest.empty:
        logger.warning("  No scored stocks data available")
        write_json(SCORED_TARGETS_JSON, {
            "targets": {},
            "symbols": {},
            "generated_at": datetime.now(timezone.utc).isoformat(),
        })
        ensure_symlink(SCORED_TARGETS_JSON, DST)
        return targets

    for _, row in latest.iterrows():
        stock = str(row.get("Stock", "")).strip()
        if not stock:
            continue
        tp = safe_float(row.get("TargetPrice"), 0.0)
        if tp > 0:
            key = normalize_ticker(stock)
            targets[key] = tp
            symbols[key] = stock

    write_json(SCORED_TARGETS_JSON, {
        "targets": targets,
        "symbols": symbols,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    })
    ensure_symlink(SCORED_TARGETS_JSON, DST)
    return targets


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 3: GENERATE PIPELINE_LATEST.JSON
# ═══════════════════════════════════════════════════════════════════════════════


def _load_latest_prices() -> Dict[str, float]:
    """Stream StockDataDB.csv and keep last close price per symbol."""
    result: Dict[str, float] = {}
    if not STOCK_DATA_DB.exists():
        return result
    try:
        with open(STOCK_DATA_DB, encoding="utf-8", errors="replace") as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                stock = (row.get("Stock") or "").strip()
                close_str = (row.get("Close") or "").strip()
                if stock and close_str:
                    try:
                        result[stock] = float(close_str)
                    except ValueError:
                        pass
    except Exception as e:
        logger.warning(f"  Could not load prices: {e}")
    return result


def _load_broker_name_mapping() -> Dict[str, str]:
    """Load BrokerName → Ticker mapping from tickers.txt."""
    mapping: Dict[str, str] = {}
    if not TICKERS_FILE.exists():
        return mapping
    try:
        with open(TICKERS_FILE, encoding="utf-8") as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                ticker = (row.get("Ticker") or "").strip()
                broker_name = (row.get("BrokerName") or "").strip()
                name = (row.get("Name") or "").strip()
                if ticker:
                    base = ticker.replace(".SA", "").strip()
                    mapping[normalize_ticker(base)] = ticker
                    if broker_name:
                        mapping[normalize_ticker(broker_name)] = ticker
                    if name:
                        mapping[normalize_ticker(name)] = ticker
    except Exception as e:
        logger.warning(f"  Could not load tickers mapping: {e}")
    return mapping


def publish_pipeline_latest(target_map: Dict[str, float]) -> None:
    """Generate pipeline_latest.json: model portfolio projected onto real values."""
    logger.info("Step 3: Generating pipeline_latest.json")

    # Load latest_run_summary.json for model stocks/weights
    summary = read_json_safe(resolve_source(LATEST_RUN_SUMMARY_JSON))
    bp = summary.get("best_portfolio_details", {})
    stocks = bp.get("stocks", [])
    weights = bp.get("weights", [])

    if not stocks:
        # Fallback: try portfolio_results_db.csv
        if PORTFOLIO_RESULTS_CSV.exists():
            try:
                df = pd.read_csv(PORTFOLIO_RESULTS_CSV)
                if not df.empty:
                    last_row = df.iloc[-1]
                    stocks_str = str(last_row.get("stocks", ""))
                    weights_str = str(last_row.get("weights", ""))
                    stocks = [s.strip() for s in stocks_str.split(",") if s.strip()]
                    weights = [safe_float(w) for w in weights_str.split(",") if w.strip()]
            except Exception:
                pass

    if not stocks:
        write_json(PIPELINE_LATEST_JSON, {
            "stocks": [], "weights": [], "rows": [], "totals": {},
            "generated_at": datetime.now(timezone.utc).isoformat(),
        })
        ensure_symlink(PIPELINE_LATEST_JSON, DST)
        return

    # Normalize weights to percentages if they look like fractions
    if weights:
        s = sum(weights)
        if 0 < s <= 1.1:
            weights = [w * 100.0 for w in weights]

    # Get available capital from ledger_positions.json
    ledger_data = read_json_safe(resolve_source(LEDGER_POSITIONS_JSON))
    total_market = safe_float(ledger_data.get("total_current_market"), 0.0)
    total_invested = safe_float(ledger_data.get("total_invested_cash"), 0.0)
    available_capital = total_market if total_market > 0 else total_invested

    # Load prices
    price_map = _load_latest_prices()

    # Build rows
    rows = []
    totals = {
        "totalPct": 0.0,
        "totalCurrentSum": 0.0,
        "totalProjectedQty": 0,
        "totalProjectedInvested": 0.0,
        "totalProjectedBRL": 0.0,
    }

    for i, stock in enumerate(stocks):
        w = safe_float(weights[i] if i < len(weights) else 0)
        totals["totalPct"] += w

        allocated = (available_capital * (w / 100.0)) if available_capital > 0 else None

        # Find current price
        current = price_map.get(stock)
        if current is None:
            norm = normalize_ticker(stock)
            for k, v in price_map.items():
                if normalize_ticker(k) == norm:
                    current = v
                    break

        # Find target price
        tp = target_map.get(normalize_ticker(stock))

        # Calculate projections
        projected_qty = None
        projected_invested = None
        projected_brl = None

        if allocated is not None and current and current > 0:
            projected_qty = int(math.floor(allocated / current))
            projected_invested = projected_qty * current
        if projected_qty is not None and tp:
            projected_brl = projected_qty * tp

        if allocated:
            totals["totalCurrentSum"] += allocated
        if projected_qty:
            totals["totalProjectedQty"] += projected_qty
        if projected_invested:
            totals["totalProjectedInvested"] += projected_invested
        if projected_brl:
            totals["totalProjectedBRL"] += projected_brl

        rows.append({
            "ticker": stock,
            "weight": w,
            "current": current,
            "projectedQty": projected_qty,
            "projectedInvested": projected_invested,
            "target": tp,
            "projectedBRL": projected_brl,
        })

    rows.sort(key=lambda r: (r.get("projectedInvested") or 0), reverse=True)

    write_json(PIPELINE_LATEST_JSON, {
        "stocks": stocks,
        "weights": weights,
        "rows": rows,
        "totals": totals,
        "used_path": str(LATEST_RUN_SUMMARY_JSON),
        "generated_at": datetime.now(timezone.utc).isoformat(),
    })
    ensure_symlink(PIPELINE_LATEST_JSON, DST)


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 4: GENERATE MIS MODEL JSON
# ═══════════════════════════════════════════════════════════════════════════════


def publish_mis_model() -> None:
    """Generate mis_model_latest.json from canonical sources."""
    logger.info("Step 4: Generating mis_model_latest.json")

    latest_summary = read_json_safe(resolve_source(LATEST_RUN_SUMMARY_JSON))
    optimized = read_json_safe(resolve_source(OPTIMIZED_RECOMMENDATION_JSON))

    bp = latest_summary.get("best_portfolio_details", {})
    comparison = optimized.get("comparison", {})
    holdings = comparison.get("holdings", {})
    ideal = comparison.get("ideal", {})
    optimal = comparison.get("optimal", {})
    momentum_val = bp.get("momentum_valuation", {})

    # Returns
    expected_return_hold = safe_float(holdings.get("expected_return_pct"), 0.0)
    expected_return_gross = safe_float(ideal.get("expected_return_pct"), 0.0)
    historical_return = safe_float(
        ideal.get("historical_return_pct"),
        safe_float(bp.get("expected_return_annual_pct"), 0.0),
    )
    expected_volatility = safe_float(bp.get("expected_volatility_annual_pct"), 0.0)

    # Transaction costs
    tx_cost_rate = safe_float(optimized.get("transaction_cost_pct_used"), 0.0003)
    portfolio_value = safe_float(holdings.get("total_value"), 0.0)

    # Sharpe
    risk_free = 11.75  # SELIC annual %
    sharpe_forward = None
    if expected_volatility > 0:
        sharpe_forward = (expected_return_gross - risk_free) / expected_volatility
    sharpe_backtest = bp.get("sharpe_ratio")
    sharpe = sharpe_forward if sharpe_forward is not None else sharpe_backtest

    # Decision
    cost_pct = safe_float(optimal.get("transition_cost_pct"), 0.0)
    net_return = expected_return_gross - cost_pct
    excess_return = net_return - expected_return_hold
    threshold = safe_float(optimized.get("min_threshold_pct"), 0.5)
    decision = "REBALANCE" if excess_return > threshold else "HOLD"

    model = {
        "meta": {
            "run_id": latest_summary.get("last_updated_run_id", ""),
            "timestamp": latest_summary.get("last_updated_timestamp", ""),
            "generated_at": datetime.now(timezone.utc).isoformat(),
        },
        "returns": {
            "hold_12m": expected_return_hold,
            "gross_12m": expected_return_gross,
            "net_12m": net_return,
            "historical_annual": historical_return,
            "excess_net_12m": excess_return,
        },
        "risk": {
            "volatility_annual": expected_volatility,
            "risk_free_annual": risk_free,
            "sharpe": sharpe,
            "sharpe_source": "forward" if sharpe_forward is not None else "backtest",
            "hhi": bp.get("concentration_risk", {}).get("hhi"),
            "top5": bp.get("concentration_risk", {}).get("top_5_holdings_pct"),
        },
        "decision": {
            "verdict": decision,
            "threshold_pct": threshold,
            "intensity": safe_float(optimal.get("blend_ratio"), 0.0) * 100,
        },
        "valuation": {
            "portfolio_pe": momentum_val.get("portfolio_forward_pe"),
            "benchmark_pe": momentum_val.get("benchmark_forward_pe"),
            "dividend_yield": momentum_val.get("portfolio_dividend_yield"),
            "momentum_signal": momentum_val.get("portfolio_momentum"),
        },
        "composition": {
            "sector_exposure": bp.get("sector_exposure_list", []),
        },
    }

    write_json(MIS_MODEL_LATEST_JSON, model)
    ensure_symlink(MIS_MODEL_LATEST_JSON, DST)

    # Also symlink model history CSV if it exists
    ensure_symlink(PORTFOLIO_RESULTS_CSV, DST, "mis_model_history.csv")


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 5: GENERATE MIS REAL JSON
# ═══════════════════════════════════════════════════════════════════════════════


def publish_mis_real() -> None:
    """Generate mis_real_latest.json from diagnostics history and portfolio history."""
    logger.info("Step 5: Generating mis_real_latest.json")

    # Read latest diagnostics row
    diag = latest_csv_rows(DIAGNOSTICS_HISTORY_CSV)
    # Read latest performance windows row
    perf_win = latest_csv_rows(PERF_WINDOWS_CSV)
    # Read portfolio history for basic stats
    history_data = read_json_safe(resolve_source(PORTFOLIO_HISTORY_JSON))
    history = history_data.get("history", []) if isinstance(history_data, dict) else []

    # Build real MIS from diagnostics CSV (populated by A4_Analysis)
    real_latest: Dict[str, Any] = {
        "meta": {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "history_start": history[0].get("date") if history else None,
            "history_end": history[-1].get("date") if history else None,
            "observations": len(history),
        },
    }

    if not diag.empty:
        row = diag.iloc[0]
        real_latest["portfolio"] = {
            "total_return_twr": safe_float(row.get("twr_total_return")),
            "annual_return": safe_float(row.get("annual_return")),
            "volatility": safe_float(row.get("annual_volatility")),
            "sharpe": safe_float(row.get("sharpe")),
            "sortino": safe_float(row.get("sortino")),
            "max_drawdown": safe_float(row.get("max_drawdown")),
            "calmar": safe_float(row.get("calmar")),
        }
        real_latest["relative"] = {
            "beta": safe_float(row.get("beta")),
            "tracking_error": safe_float(row.get("tracking_error")),
            "information_ratio": safe_float(row.get("information_ratio")),
            "correlation": safe_float(row.get("correlation_vs_benchmark")),
        }
        real_latest["structure"] = {
            "hhi": safe_float(row.get("hhi")),
            "top3": safe_float(row.get("top3_concentration")),
            "top5": safe_float(row.get("top5_concentration")),
            "n_assets": int(safe_float(row.get("n_assets"), 0)),
        }
    else:
        real_latest["portfolio"] = {}
        real_latest["relative"] = {}
        real_latest["structure"] = {}

    # Performance windows
    if not perf_win.empty:
        row = perf_win.iloc[0]
        real_latest["performance"] = {}
        for window in ["ytd", "3m", "6m", "12m", "24m"]:
            real_latest["performance"][window.upper()] = {
                "portfolio": safe_float(row.get(f"perf_{window}_portfolio")),
                "benchmark": safe_float(row.get(f"perf_{window}_benchmark")),
            }
    else:
        real_latest["performance"] = {}

    write_json(MIS_REAL_LATEST_JSON, real_latest)
    ensure_symlink(MIS_REAL_LATEST_JSON, DST)

    # Symlink history CSVs
    ensure_symlink(DIAGNOSTICS_HISTORY_CSV, DST, "mis_real_history.csv")
    ensure_symlink(ASSET_ATTRIBUTION_CSV, DST, "mis_real_attribution.csv")


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 6: GENERATE PROCESSED_NOTES.JSON COPY
# ═══════════════════════════════════════════════════════════════════════════════


def publish_processed_notes() -> None:
    """Symlink processed_notes.json if it exists in data/."""
    logger.info("Step 6: Linking processed_notes.json")
    src = SRC / "processed_notes.json"
    if src.exists():
        ensure_symlink(src, DST)
    else:
        # May still be in html/data/ from B1 (transition)
        dst = DST / "processed_notes.json"
        if dst.exists():
            logger.info("  processed_notes.json already in html/data/")
        else:
            logger.warning("  processed_notes.json not found")


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 7: SYMLINK PROGRESS FILES
# ═══════════════════════════════════════════════════════════════════════════════


def publish_progress_symlinks() -> None:
    """Ensure progress JSONs in data/ are symlinked into html/data/.

    Progress files are written live by engines during execution.
    If the canonical file in data/ doesn't exist yet, create an empty
    placeholder so the symlink target is valid.
    """
    logger.info("Step 7: Symlinking progress files")
    for name in PROGRESS_FILES:
        canonical = PROGRESS_DIR / name
        # If progress file only exists in html/data/ (transition), move it
        dst = DST / name
        if not canonical.exists() and dst.exists() and not dst.is_symlink():
            dst.rename(canonical)
            logger.info(f"  Migrated {name} → data/")
        # Create empty placeholder if needed
        if not canonical.exists():
            canonical.parent.mkdir(parents=True, exist_ok=True)
            canonical.write_text("{}", encoding="utf-8")
            logger.info(f"  Created empty {name}")
        ensure_symlink(canonical, DST)


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════


def main() -> int:
    start_time = datetime.now()
    logger.info(f"D_Publish.py v{D_PUBLISH_VERSION} — Starting frontend asset publication")
    logger.info(f"Source: {SRC}")
    logger.info(f"Target: {DST}")

    DST.mkdir(parents=True, exist_ok=True)

    try:
        # Step 0: Generate derived snapshot JSONs from history CSVs
        publish_derived_snapshots()

        # Step 1: Symlink canonical files
        publish_symlink_files()

        # Step 2: Generate scored_targets.json
        target_map = publish_scored_targets()

        # Step 3: Generate pipeline_latest.json
        publish_pipeline_latest(target_map)

        # Step 4: Generate MIS Model
        publish_mis_model()

        # Step 5: Generate MIS Real
        publish_mis_real()

        # Step 6: Processed notes
        publish_processed_notes()

        # Step 7: Progress file symlinks
        publish_progress_symlinks()

        elapsed = (datetime.now() - start_time).total_seconds()
        logger.info(f"D_Publish.py completed in {elapsed:.1f}s")
        return 0

    except Exception as e:
        logger.critical(f"D_Publish.py failed: {e}", exc_info=True)
        return 1


if __name__ == "__main__":
    sys.exit(main())



