#!/usr/bin/env python3
"""
engines/D_Publish.py — Frontend Asset Publisher

Single point of contact between the canonical data store (data/) and the
frontend cache (html/data/).  No other engine should write to html/data/
(except progress JSONs written live during execution).

Responsibilities:
  1. Symlink canonical CSVs/JSONs from data/ → html/data/
  2. Generate derived "latest" JSON snapshots from historical CSVs
  3. Generate pipeline_latest.json (model projected onto real portfolio value)
  4. Generate scored_targets.json
  5. Generate MIS JSONs (model + real)

Usage:
    python3 engines/D_Publish.py
"""

# --- Script Version ---
D_PUBLISH_VERSION = "3.1.0"  # Real CDI data from LFTS11 via A1_Download

import csv
import json
import math
import os
import sys
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

# Ensure project root is on sys.path
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

# ═══════════════════════════════════════════════════════════════════════════════
# PATHS — Canonical sources (data/) and targets (html/data/)
# ═══════════════════════════════════════════════════════════════════════════════

SRC = ROOT / "data"
DST = ROOT / "html" / "data"

# --- Canonical source files ---
FINDB_DIR = SRC / "findb"
STOCK_DATA_DB = FINDB_DIR / "StockDataDB.csv"
FINANCIALS_DB = FINDB_DIR / "FinancialsDB.csv"

# CDI proxy: LFTS11.SA (It Now Tesouro Selic ETF), downloaded by A1_Download
CDI_PROXY_TICKER = "LFTS11.SA"
SELIC_ANNUAL_FALLBACK = 0.1175  # Fallback if LFTS11 data unavailable

RESULTS_DIR = SRC / "results"
SCORED_STOCKS_CSV = RESULTS_DIR / "scored_stocks.csv"
SECTOR_PE_CSV = RESULTS_DIR / "sector_pe.csv"
CORRELATION_MATRIX_CSV = RESULTS_DIR / "correlation_matrix.csv"
PORTFOLIO_RESULTS_CSV = RESULTS_DIR / "portfolio_results_db.csv"
GA_FITNESS_CSV = RESULTS_DIR / "ga_fitness_noise_db.csv"
OPTIMIZED_HISTORY_JSONL = RESULTS_DIR / "optimized_portfolio_history.jsonl"
DIAGNOSTICS_HISTORY_CSV = RESULTS_DIR / "portfolio_diagnostics_history.csv"
ATTRIBUTION_HISTORY_CSV = RESULTS_DIR / "performance_attribution_history.csv"
ASSET_ATTRIBUTION_CSV = RESULTS_DIR / "asset_attribution_history.csv"
PERF_WINDOWS_CSV = RESULTS_DIR / "performance_windows_history.csv"
SCORING_PERF_CSV = RESULTS_DIR / "scoring_performance.csv"
PORTFOLIO_PERF_CSV = RESULTS_DIR / "portfolio_performance.csv"
DOWNLOAD_PERF_CSV = RESULTS_DIR / "download_performance.csv"

LEDGER_CSV = SRC / "ledger.csv"
LATEST_RUN_SUMMARY_JSON = RESULTS_DIR / "latest_run_summary.json"
OPTIMIZED_RECOMMENDATION_JSON = RESULTS_DIR / "optimized_recommendation.json"
LEDGER_POSITIONS_JSON = SRC / "ledger_positions.json"
PORTFOLIO_HISTORY_CSV = SRC / "portfolio_history.csv"
PORTFOLIO_TIMESERIES_CSV = RESULTS_DIR / "portfolio_timeseries.csv"
DIAGNOSTICS_JSON = RESULTS_DIR / "portfolio_diagnostics.json"
ATTRIBUTION_JSON = RESULTS_DIR / "performance_attribution.json"

TICKERS_FILE = ROOT / "parameters" / "tickers.txt"

# --- New: Real daily returns CSV (Mudança 1) ---
PORTFOLIO_REAL_DAILY_CSV = RESULTS_DIR / "portfolio_real_daily.csv"

# --- Derived files (generated by D_Publish, stored in data/results/) ---
DERIVED_DIR = RESULTS_DIR
SCORED_TARGETS_JSON = DERIVED_DIR / "scored_targets.json"
PIPELINE_LATEST_JSON = DERIVED_DIR / "pipeline_latest.json"
DASHBOARD_LATEST_JSON = DERIVED_DIR / "dashboard_latest.json"

# --- Progress files (written live by engines, canonical in data/) ---
PROGRESS_DIR = SRC
PROGRESS_FILES = [
    "pipeline_progress.json",
    "download_progress.json",
    "scoring_progress.json",
    "portfolio_progress.json",
]

# Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - D_Publish - %(levelname)s - %(message)s",
)
logger = logging.getLogger("D_Publish")


# ═══════════════════════════════════════════════════════════════════════════════
# UTILITIES
# ═══════════════════════════════════════════════════════════════════════════════


def safe_float(v: Any, default: float = 0.0) -> float:
    """Safely convert a value to float."""
    if v is None or v == "":
        return default
    try:
        return float(v)
    except (TypeError, ValueError):
        return default


def sanitize_for_json(value: Any) -> Any:
    """Replace NaN/Inf with None for JSON serialization."""
    if isinstance(value, dict):
        return {k: sanitize_for_json(v) for k, v in value.items()}
    if isinstance(value, list):
        return [sanitize_for_json(v) for v in value]
    if isinstance(value, float):
        if not math.isfinite(value):
            return None
    return value


def write_json(path: Path, payload: dict) -> None:
    """Write JSON with NaN sanitization."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(sanitize_for_json(payload), f, indent=2, ensure_ascii=False, allow_nan=False)
    logger.info(f"  Wrote {path.name}")


def ensure_symlink(src: Path, dst_dir: Path, dst_name: Optional[str] = None) -> bool:
    """Create a symlink in dst_dir pointing to src.  Returns True on success.

    If the destination already exists:
      - If it's a symlink pointing to src → no-op
      - If it's a symlink pointing elsewhere → replace
      - If it's a regular file → remove and replace with symlink
    Uses *absolute* paths so the link works regardless of cwd.
    """
    if not src.exists():
        logger.warning(f"  Source not found, skipping: {src.name}")
        return False

    src_abs = src.resolve()
    dst = dst_dir / (dst_name or src.name)
    dst.parent.mkdir(parents=True, exist_ok=True)

    # Already a correct symlink?
    if dst.is_symlink():
        try:
            if dst.resolve() == src_abs:
                logger.info(f"  {dst.name} ✓ symlink OK")
                return True
        except OSError:
            pass
        # Wrong target — remove and recreate
        dst.unlink()

    # Regular file occupying the slot — remove it
    if dst.exists():
        dst.unlink()

    os.symlink(src_abs, dst)
    logger.info(f"  {dst.name} → {src_abs}")
    return True


def read_json_safe(path: Path) -> dict:
    """Read a JSON file, returning empty dict if missing or corrupt."""
    if not path.exists():
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        logger.warning(f"  Could not read {path.name}: {e}")
        return {}


def latest_csv_rows(path: Path, run_id_col: str = "run_id") -> pd.DataFrame:
    """Read a CSV and return only rows from the latest run_id."""
    if not path.exists():
        return pd.DataFrame()
    try:
        df = pd.read_csv(path)
        if run_id_col not in df.columns or df.empty:
            return df
        latest = df[run_id_col].max()
        return df[df[run_id_col] == latest].copy()
    except Exception as e:
        logger.warning(f"  Could not read {path.name}: {e}")
        return pd.DataFrame()


def normalize_ticker(s: Optional[str]) -> str:
    """Normalize string for ticker matching (uppercase, alphanum only)."""
    if not s:
        return ""
    return "".join(c for c in str(s).upper() if c.isalnum())


def resolve_source(canonical: Path, fallback_name: Optional[str] = None) -> Path:
    """Return canonical path if it exists, otherwise fall back to html/data/.

    During the transition period some files may only exist in html/data/ because
    the pipeline hasn't been fully re-run yet.  This helper transparently picks
    whichever copy is available (preferring canonical).
    """
    if canonical.exists():
        return canonical
    fb = DST / (fallback_name or canonical.name)
    if fb.exists():
        logger.debug(f"  Fallback: using {fb} (canonical {canonical} not yet created)")
        return fb
    return canonical  # caller will handle missing file


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 0: GENERATE DERIVED SNAPSHOT JSONs FROM HISTORY CSVs
# ═══════════════════════════════════════════════════════════════════════════════


def publish_derived_snapshots() -> None:
    """Generate snapshot JSONs from the latest row of their history CSVs.

    These files used to be written directly by A4_Analysis.py.  Now A4 only
    appends to the history CSVs and D_Publish derives the snapshot JSONs,
    eliminating the duplication.

    Generated files (in data/results/):
      - portfolio_diagnostics.json   ← from portfolio_diagnostics_history.csv
      - performance_attribution.json ← from performance_attribution_history.csv
    """
    logger.info("Step 0: Generating derived snapshot JSONs from history CSVs")

    # --- portfolio_diagnostics.json ---
    diag = latest_csv_rows(DIAGNOSTICS_HISTORY_CSV)
    if not diag.empty:
        row = diag.iloc[0]
        payload = {k: (None if pd.isna(v) else v) for k, v in row.to_dict().items()}
        write_json(DIAGNOSTICS_JSON, payload)
        ensure_symlink(DIAGNOSTICS_JSON, DST)
    else:
        logger.warning("  No diagnostics history data — skipping portfolio_diagnostics.json")

    # --- performance_attribution.json ---
    attr = latest_csv_rows(ATTRIBUTION_HISTORY_CSV)
    if not attr.empty:
        row = attr.iloc[0]
        payload = {k: (None if pd.isna(v) else v) for k, v in row.to_dict().items()}
        write_json(ATTRIBUTION_JSON, payload)
        ensure_symlink(ATTRIBUTION_JSON, DST)
    else:
        logger.warning("  No attribution history data — skipping performance_attribution.json")


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 1: COPY CANONICAL FILES
# ═══════════════════════════════════════════════════════════════════════════════


def publish_symlink_files() -> None:
    """Create symlinks in html/data/ pointing to canonical files in data/."""
    logger.info("Step 1: Symlinking canonical files to html/data/")

    # CSVs from data/results/
    ensure_symlink(SCORED_STOCKS_CSV, DST)
    ensure_symlink(SECTOR_PE_CSV, DST)
    ensure_symlink(CORRELATION_MATRIX_CSV, DST)
    ensure_symlink(PORTFOLIO_RESULTS_CSV, DST)  # also exposed as mis_model_history.csv (Step 4)
    ensure_symlink(GA_FITNESS_CSV, DST)
    ensure_symlink(SCORING_PERF_CSV, DST)
    ensure_symlink(PORTFOLIO_PERF_CSV, DST)
    ensure_symlink(DOWNLOAD_PERF_CSV, DST)

    # StockDataDB
    ensure_symlink(STOCK_DATA_DB, DST)

    # Ledger CSV
    ensure_symlink(LEDGER_CSV, DST)

    # Tickers file
    ensure_symlink(TICKERS_FILE, DST)

    # JSONs — use resolve_source to fallback to html/data/ during transition
    # Note: DIAGNOSTICS_JSON and ATTRIBUTION_JSON are generated by
    # publish_derived_snapshots() and symlinked there.
    for json_src in [LATEST_RUN_SUMMARY_JSON, OPTIMIZED_RECOMMENDATION_JSON,
                     LEDGER_POSITIONS_JSON]:
        resolved = resolve_source(json_src)
        # Only symlink if the resolved source is outside html/data/
        if resolved.parent != DST:
            ensure_symlink(resolved, DST, json_src.name)

    # Portfolio history CSV (migrated from JSON in Phase 3.3)
    ensure_symlink(PORTFOLIO_HISTORY_CSV, DST)

    # Portfolio timeseries
    resolved_ts = resolve_source(PORTFOLIO_TIMESERIES_CSV)
    if resolved_ts.parent != DST:
        ensure_symlink(resolved_ts, DST, PORTFOLIO_TIMESERIES_CSV.name)


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 2: GENERATE SCORED_TARGETS.JSON
# ═══════════════════════════════════════════════════════════════════════════════


def publish_scored_targets() -> Dict[str, float]:
    """Generate scored_targets.json from latest scored_stocks.csv run."""
    logger.info("Step 2: Generating scored_targets.json")

    targets: Dict[str, float] = {}
    symbols: Dict[str, str] = {}

    latest = latest_csv_rows(SCORED_STOCKS_CSV)
    if latest.empty:
        logger.warning("  No scored stocks data available")
        write_json(SCORED_TARGETS_JSON, {
            "targets": {},
            "symbols": {},
            "generated_at": datetime.now(timezone.utc).isoformat(),
        })
        ensure_symlink(SCORED_TARGETS_JSON, DST)
        return targets

    for _, row in latest.iterrows():
        stock = str(row.get("Stock", "")).strip()
        if not stock:
            continue
        tp = safe_float(row.get("TargetPrice"), 0.0)
        if tp > 0:
            key = normalize_ticker(stock)
            targets[key] = tp
            symbols[key] = stock

    write_json(SCORED_TARGETS_JSON, {
        "targets": targets,
        "symbols": symbols,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    })
    ensure_symlink(SCORED_TARGETS_JSON, DST)
    return targets


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 3: GENERATE PIPELINE_LATEST.JSON
# ═══════════════════════════════════════════════════════════════════════════════


def _load_latest_prices() -> Dict[str, float]:
    """Stream StockDataDB.csv and keep last close price per symbol."""
    result: Dict[str, float] = {}
    if not STOCK_DATA_DB.exists():
        return result
    try:
        with open(STOCK_DATA_DB, encoding="utf-8", errors="replace") as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                stock = (row.get("Stock") or "").strip()
                close_str = (row.get("Close") or "").strip()
                if stock and close_str:
                    try:
                        result[stock] = float(close_str)
                    except ValueError:
                        pass
    except Exception as e:
        logger.warning(f"  Could not load prices: {e}")
    return result


def _load_broker_name_mapping() -> Dict[str, str]:
    """Load BrokerName → Ticker mapping from tickers.txt."""
    mapping: Dict[str, str] = {}
    if not TICKERS_FILE.exists():
        return mapping
    try:
        with open(TICKERS_FILE, encoding="utf-8") as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                ticker = (row.get("Ticker") or "").strip()
                broker_name = (row.get("BrokerName") or "").strip()
                name = (row.get("Name") or "").strip()
                if ticker:
                    base = ticker.replace(".SA", "").strip()
                    mapping[normalize_ticker(base)] = ticker
                    if broker_name:
                        mapping[normalize_ticker(broker_name)] = ticker
                    if name:
                        mapping[normalize_ticker(name)] = ticker
    except Exception as e:
        logger.warning(f"  Could not load tickers mapping: {e}")
    return mapping


def publish_pipeline_latest(target_map: Dict[str, float]) -> None:
    """Generate pipeline_latest.json: model portfolio projected onto real values."""
    logger.info("Step 3: Generating pipeline_latest.json")

    # Load latest_run_summary.json for model stocks/weights
    summary = read_json_safe(resolve_source(LATEST_RUN_SUMMARY_JSON))
    bp = summary.get("best_portfolio_details", {})
    stocks = bp.get("stocks", [])
    weights = bp.get("weights", [])

    if not stocks:
        # Fallback: try portfolio_results_db.csv
        if PORTFOLIO_RESULTS_CSV.exists():
            try:
                df = pd.read_csv(PORTFOLIO_RESULTS_CSV)
                if not df.empty:
                    last_row = df.iloc[-1]
                    stocks_str = str(last_row.get("stocks", ""))
                    weights_str = str(last_row.get("weights", ""))
                    stocks = [s.strip() for s in stocks_str.split(",") if s.strip()]
                    weights = [safe_float(w) for w in weights_str.split(",") if w.strip()]
            except Exception:
                pass

    if not stocks:
        write_json(PIPELINE_LATEST_JSON, {
            "stocks": [], "weights": [], "rows": [], "totals": {},
            "generated_at": datetime.now(timezone.utc).isoformat(),
        })
        ensure_symlink(PIPELINE_LATEST_JSON, DST)
        return

    # Normalize weights to percentages if they look like fractions
    if weights:
        s = sum(weights)
        if 0 < s <= 1.1:
            weights = [w * 100.0 for w in weights]

    # Get available capital from ledger_positions.json
    ledger_data = read_json_safe(resolve_source(LEDGER_POSITIONS_JSON))
    total_market = safe_float(ledger_data.get("total_current_market"), 0.0)
    total_invested = safe_float(ledger_data.get("total_invested_cash"), 0.0)
    available_capital = total_market if total_market > 0 else total_invested

    # Load prices
    price_map = _load_latest_prices()

    # Build rows
    rows = []
    totals = {
        "totalPct": 0.0,
        "totalCurrentSum": 0.0,
        "totalProjectedQty": 0,
        "totalProjectedInvested": 0.0,
        "totalProjectedBRL": 0.0,
    }

    for i, stock in enumerate(stocks):
        w = safe_float(weights[i] if i < len(weights) else 0)
        totals["totalPct"] += w

        allocated = (available_capital * (w / 100.0)) if available_capital > 0 else None

        # Find current price
        current = price_map.get(stock)
        if current is None:
            norm = normalize_ticker(stock)
            for k, v in price_map.items():
                if normalize_ticker(k) == norm:
                    current = v
                    break

        # Find target price
        tp = target_map.get(normalize_ticker(stock))

        # Calculate projections
        projected_qty = None
        projected_invested = None
        projected_brl = None

        if allocated is not None and current and current > 0:
            projected_qty = int(math.floor(allocated / current))
            projected_invested = projected_qty * current
        if projected_qty is not None and tp:
            projected_brl = projected_qty * tp

        if allocated:
            totals["totalCurrentSum"] += allocated
        if projected_qty:
            totals["totalProjectedQty"] += projected_qty
        if projected_invested:
            totals["totalProjectedInvested"] += projected_invested
        if projected_brl:
            totals["totalProjectedBRL"] += projected_brl

        rows.append({
            "ticker": stock,
            "weight": w,
            "current": current,
            "projectedQty": projected_qty,
            "projectedInvested": projected_invested,
            "target": tp,
            "projectedBRL": projected_brl,
        })

    rows.sort(key=lambda r: (r.get("projectedInvested") or 0), reverse=True)

    write_json(PIPELINE_LATEST_JSON, {
        "stocks": stocks,
        "weights": weights,
        "rows": rows,
        "totals": totals,
        "used_path": str(LATEST_RUN_SUMMARY_JSON),
        "generated_at": datetime.now(timezone.utc).isoformat(),
    })
    ensure_symlink(PIPELINE_LATEST_JSON, DST)


# ═══════════════════════════════════════════════════════════════════════════════
# CDI DAILY RETURNS LOADER
# ═══════════════════════════════════════════════════════════════════════════════


def _load_cdi_daily_returns() -> Tuple[Dict[str, float], str]:
    """Load real CDI daily returns from LFTS11.SA in StockDataDB.csv.

    Returns:
        (dict mapping date_str → daily_return, source_label)
    Falls back to SELIC synthetic flat rate if LFTS11 data is unavailable.
    """
    cdi_by_date: Dict[str, float] = {}
    source = "SELIC flat rate (fallback)"

    if STOCK_DATA_DB.exists():
        try:
            df = pd.read_csv(STOCK_DATA_DB)
            cdi_df = df[df["Stock"] == CDI_PROXY_TICKER].copy()
            if not cdi_df.empty:
                cdi_df["Date"] = pd.to_datetime(cdi_df["Date"], errors="coerce")
                cdi_df = cdi_df.dropna(subset=["Date"]).sort_values("Date")
                cdi_df["daily_return"] = cdi_df["Close"].pct_change()
                for _, row in cdi_df.iterrows():
                    dt = row["Date"].strftime("%Y-%m-%d")
                    dr = row["daily_return"]
                    if pd.notna(dr):
                        cdi_by_date[dt] = float(dr)
                source = f"{CDI_PROXY_TICKER} (real)"
                logger.info(f"  Loaded {len(cdi_by_date)} CDI daily returns from {CDI_PROXY_TICKER}")
        except Exception as e:
            logger.warning(f"  Could not load CDI data from StockDataDB: {e}")

    if not cdi_by_date:
        logger.warning(f"  {CDI_PROXY_TICKER} not found in StockDataDB — using SELIC flat rate fallback")

    return cdi_by_date, source


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 4a: GENERATE PORTFOLIO_REAL_DAILY.CSV (Mudança 1)
# ═══════════════════════════════════════════════════════════════════════════════


def _build_real_daily_series() -> pd.DataFrame:
    """Build the real daily returns CSV from portfolio_history + ledger + timeseries.

    Output columns: date, portfolio_value, cost_basis, cash_flow,
                    portfolio_return, benchmark_return, cdi_return

    Returns an empty DataFrame if source data is insufficient.
    """
    logger.info("Step 4a: Building portfolio_real_daily.csv")

    # --- Load portfolio_history.csv → {date: portfolio_value, cost_basis} ---
    if not PORTFOLIO_HISTORY_CSV.exists():
        logger.warning("  portfolio_history.csv not found — skipping real daily series")
        return pd.DataFrame()

    hist = pd.read_csv(PORTFOLIO_HISTORY_CSV)
    if hist.empty:
        return pd.DataFrame()

    # Group by date → one row per date (market_value & cost_basis are already totals)
    hist_daily = hist.groupby("date").agg(
        portfolio_value=("market_value", "first"),
        cost_basis=("cost_basis", "first"),
    ).reset_index().sort_values("date")

    # --- Load ledger.csv → cash flows by date ---
    cf_by_date: Dict[str, float] = {}
    if LEDGER_CSV.exists():
        ledger = pd.read_csv(LEDGER_CSV)
        for _, row in ledger.iterrows():
            dt = str(row.get("trade_date", "")).strip()[:10]
            side = str(row.get("side", "")).upper()
            total_cost = safe_float(row.get("total_cost"), 0.0)
            # BUY = cash out (positive CF into portfolio), SELL = cash in (negative)
            cf = total_cost if side == "BUY" else -total_cost
            cf_by_date[dt] = cf_by_date.get(dt, 0.0) + cf

    # --- Load portfolio_timeseries.csv → benchmark daily returns ---
    bench_by_date: Dict[str, float] = {}
    ts_path = resolve_source(PORTFOLIO_TIMESERIES_CSV)
    if ts_path.exists():
        ts = pd.read_csv(ts_path)
        for _, row in ts.iterrows():
            dt = str(row.get("date", "")).strip()[:10]
            br = safe_float(row.get("benchmark1_daily_return"), None)
            if br is not None:
                bench_by_date[dt] = br

    # --- Load CDI daily returns (real from LFTS11 or SELIC fallback) ---
    cdi_by_date, cdi_source = _load_cdi_daily_returns()
    cdi_is_synthetic = "fallback" in cdi_source
    selic_daily_fallback = (1 + SELIC_ANNUAL_FALLBACK) ** (1 / 252) - 1

    # --- Build daily series (only dates present in portfolio_history, already business-days) ---
    dates = hist_daily["date"].tolist()
    rows = []

    for i, dt in enumerate(dates):
        pv = hist_daily.iloc[i]["portfolio_value"]
        cb = hist_daily.iloc[i]["cost_basis"]
        cf = cf_by_date.get(dt, 0.0)

        if i == 0:
            port_ret = None
            bench_ret = None
            cdi_ret = None
        else:
            prev_pv = hist_daily.iloc[i - 1]["portfolio_value"]
            prev_cb = hist_daily.iloc[i - 1]["cost_basis"]

            # Determine actual cash flow for TWR calculation
            # If cost_basis changed, there was a real transaction
            cost_delta = cb - prev_cb
            if abs(cost_delta) > 0.01:
                # Use cost_basis delta as cash flow (more reliable than ledger
                # because it's already aligned with the tracked portfolio)
                effective_cf = cost_delta
            else:
                effective_cf = 0.0

            # TWR daily return: r = (V_t - CF_t) / V_{t-1} - 1
            if prev_pv > 0:
                port_ret = (pv - effective_cf) / prev_pv - 1
            else:
                port_ret = None

            bench_ret = bench_by_date.get(dt, None)

            # CDI: real data from LFTS11, fallback to synthetic
            cdi_ret = cdi_by_date.get(dt, selic_daily_fallback if cdi_is_synthetic else None)

        rows.append({
            "date": dt,
            "portfolio_value": round(pv, 2),
            "cost_basis": round(cb, 2),
            "cash_flow": round(cf, 2),
            "portfolio_return": round(port_ret, 8) if port_ret is not None else "",
            "benchmark_return": round(bench_ret, 8) if bench_ret is not None else "",
            "cdi_return": round(cdi_ret, 8) if cdi_ret is not None else "",
        })

    df = pd.DataFrame(rows)
    if not df.empty:
        df.to_csv(PORTFOLIO_REAL_DAILY_CSV, index=False)
        logger.info(f"  Wrote {PORTFOLIO_REAL_DAILY_CSV.name} ({len(df)} rows)")
        ensure_symlink(PORTFOLIO_REAL_DAILY_CSV, DST)

    return df


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 4b: COMPUTE REAL TWR METRICS (Mudança 2)
# ═══════════════════════════════════════════════════════════════════════════════


def _compute_real_metrics(daily_df: pd.DataFrame) -> dict:
    """Compute TWR-based metrics from the real daily series.

    Returns a dict with twr, benchmark, alpha, and relative sub-dicts.
    """
    if daily_df.empty:
        return {}

    # Extract return series (skip first row which has no return)
    port_rets = pd.to_numeric(daily_df["portfolio_return"], errors="coerce").dropna()
    bench_rets = pd.to_numeric(daily_df["benchmark_return"], errors="coerce").dropna()

    if port_rets.empty:
        return {}

    n = len(port_rets)

    # --- CDI metrics (real data from LFTS11 or SELIC fallback) ---
    # Computed first so we can use actual CDI annual rate as risk-free
    cdi_rets = pd.to_numeric(daily_df["cdi_return"], errors="coerce").dropna()
    if not cdi_rets.empty:
        cdi_total = float(np.prod(1 + cdi_rets.values) - 1)
        cdi_annual = float((1 + cdi_total) ** (252 / len(cdi_rets)) - 1) if len(cdi_rets) > 0 else SELIC_ANNUAL_FALLBACK
        cdi_source = CDI_PROXY_TICKER
    else:
        cdi_daily_fb = (1 + SELIC_ANNUAL_FALLBACK) ** (1 / 252) - 1
        cdi_total = (1 + cdi_daily_fb) ** n - 1
        cdi_annual = SELIC_ANNUAL_FALLBACK
        cdi_source = "SELIC flat rate (fallback)"

    risk_free_annual = cdi_annual  # Use real CDI rate as risk-free

    # --- Portfolio TWR metrics ---
    total_return = float(np.prod(1 + port_rets.values) - 1)
    annual_return = float((1 + total_return) ** (252 / n) - 1) if n > 0 else 0.0
    volatility = float(port_rets.std(ddof=1) * np.sqrt(252)) if n > 1 else 0.0
    sharpe = float((annual_return - risk_free_annual) / volatility) if volatility > 0 else None
    
    # Sortino
    downside = port_rets[port_rets < 0]
    downside_dev = float(downside.std(ddof=1) * np.sqrt(252)) if len(downside) > 1 else 0.0
    sortino = float((annual_return - risk_free_annual) / downside_dev) if downside_dev > 0 else None

    # Max drawdown (compute from TWR index)
    idx = np.cumprod(1 + port_rets.values)
    peak = np.maximum.accumulate(idx)
    dd = (idx - peak) / peak
    max_drawdown = float(abs(dd.min())) if len(dd) > 0 else 0.0

    # Calmar
    calmar = float(annual_return / max_drawdown) if max_drawdown > 0 else None

    # --- Benchmark metrics (same dates) ---
    # Align benchmark to same index as portfolio returns
    common_idx = port_rets.index.intersection(bench_rets.index)
    port_common = port_rets.loc[common_idx]
    bench_common = bench_rets.loc[common_idx]

    bench_total = float(np.prod(1 + bench_common.values) - 1) if len(bench_common) > 0 else 0.0
    n_bench = len(bench_common)
    bench_annual = float((1 + bench_total) ** (252 / n_bench) - 1) if n_bench > 0 else 0.0

    # --- Alpha ---
    alpha_total = total_return - bench_total
    alpha_annual = annual_return - bench_annual

    # --- Relative metrics ---
    beta = None
    tracking_error = None
    information_ratio = None
    correlation = None

    if len(port_common) > 1 and bench_common.std() > 0:
        cov_matrix = np.cov(port_common.values, bench_common.values)
        beta = float(cov_matrix[0, 1] / cov_matrix[1, 1])

        diff = port_common.values - bench_common.values
        tracking_error = float(np.std(diff, ddof=1) * np.sqrt(252))
        if tracking_error > 0:
            information_ratio = float(alpha_annual / tracking_error)

        corr_val = np.corrcoef(port_common.values, bench_common.values)[0, 1]
        correlation = float(corr_val) if np.isfinite(corr_val) else None

    # % do CDI: standard Brazilian fund metric
    pct_cdi = round((total_return / cdi_total) * 100, 1) if cdi_total > 0 else None

    # Annualization safety flag: annualized numbers are unreliable under 1 year
    annualize_safe = n >= 252

    # --- Performance windows ---
    performance = _compute_performance_windows(daily_df)

    return {
        "twr": {
            "total_return": round(total_return, 4),
            "annual_return": round(annual_return, 4),
            "volatility": round(volatility, 4),
            "sharpe": round(sharpe, 2) if sharpe is not None else None,
            "sortino": round(sortino, 2) if sortino is not None else None,
            "max_drawdown": round(max_drawdown, 4),
            "calmar": round(calmar, 2) if calmar is not None else None,
            "pct_cdi": pct_cdi,
            "risk_free_annual": round(risk_free_annual, 4),
        },
        "benchmark": {
            "ticker": "^BVSP",
            "total_return": round(bench_total, 4),
            "annual_return": round(bench_annual, 4),
        },
        "cdi": {
            "total_return": round(cdi_total, 4),
            "annual_rate": round(cdi_annual, 4),
            "source": cdi_source,
        },
        "alpha": {
            "total": round(alpha_total, 4),
            "annual": round(alpha_annual, 4),
        },
        "relative": {
            "beta": round(beta, 2) if beta is not None else None,
            "tracking_error": round(tracking_error, 4) if tracking_error is not None else None,
            "information_ratio": round(information_ratio, 2) if information_ratio is not None else None,
            "correlation": round(correlation, 2) if correlation is not None else None,
        },
        "annualize_safe": annualize_safe,
        "performance": performance,
    }


def _compute_performance_windows(daily_df: pd.DataFrame) -> dict:
    """Compute portfolio, benchmark & CDI returns for standard time windows.

    Windows: YTD, 3M, 6M, 12M, 24M — computed from the real daily series.
    Each window includes portfolio, benchmark, cdi, and pct_cdi.
    """
    if daily_df.empty:
        return {}

    df = daily_df.copy()
    df["date_dt"] = pd.to_datetime(df["date"])
    df["port_r"] = pd.to_numeric(df["portfolio_return"], errors="coerce")
    df["bench_r"] = pd.to_numeric(df["benchmark_return"], errors="coerce")
    df["cdi_r"] = pd.to_numeric(df["cdi_return"], errors="coerce")

    last_date = df["date_dt"].max()
    result = {}


    windows = {
        "YTD": pd.Timestamp(last_date.year, 1, 1),
        "3M": last_date - pd.DateOffset(months=3),
        "6M": last_date - pd.DateOffset(months=6),
        "12M": last_date - pd.DateOffset(months=12),
        "24M": last_date - pd.DateOffset(months=24),
    }

    for label, start in windows.items():
        subset = df[df["date_dt"] >= start]
        port_r = subset["port_r"].dropna()
        bench_r = subset["bench_r"].dropna()
        cdi_r = subset["cdi_r"].dropna()

        if port_r.empty:
            continue

        p_total = float(np.prod(1 + port_r.values) - 1)
        b_total = float(np.prod(1 + bench_r.values) - 1) if not bench_r.empty else None
        c_total = float(np.prod(1 + cdi_r.values) - 1) if not cdi_r.empty else None
        pct_cdi = round((p_total / c_total) * 100, 1) if c_total and c_total > 0 else None

        result[label] = {
            "portfolio": round(p_total, 4),
            "benchmark": round(b_total, 4) if b_total is not None else None,
            "cdi": round(c_total, 4),
            "pct_cdi": pct_cdi,
        }

    return result


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 4: GENERATE DASHBOARD_LATEST.JSON (consolidated model + real)
# ═══════════════════════════════════════════════════════════════════════════════


def _build_model_section() -> dict:
    """Build the 'model' section of dashboard_latest.json."""
    latest_summary = read_json_safe(resolve_source(LATEST_RUN_SUMMARY_JSON))
    optimized = read_json_safe(resolve_source(OPTIMIZED_RECOMMENDATION_JSON))

    bp = latest_summary.get("best_portfolio_details", {})
    comparison = optimized.get("comparison", {})
    holdings = comparison.get("holdings", {})
    ideal = comparison.get("ideal", {})
    optimal = comparison.get("optimal", {})
    momentum_val = bp.get("momentum_valuation", {})

    # Returns
    expected_return_hold = safe_float(holdings.get("expected_return_pct"), 0.0)
    expected_return_gross = safe_float(ideal.get("expected_return_pct"), 0.0)
    historical_return = safe_float(
        ideal.get("historical_return_pct"),
        safe_float(bp.get("expected_return_annual_pct"), 0.0),
    )
    expected_volatility = safe_float(bp.get("expected_volatility_annual_pct"), 0.0)

    # Sharpe
    risk_free = 11.75  # SELIC annual %
    sharpe_forward = None
    if expected_volatility > 0:
        sharpe_forward = (expected_return_gross - risk_free) / expected_volatility
    sharpe_backtest = bp.get("sharpe_forward", bp.get("sharpe_ratio"))
    sharpe = sharpe_forward if sharpe_forward is not None else sharpe_backtest

    # Decision
    cost_pct = safe_float(optimal.get("transition_cost_pct"), 0.0)
    net_return = expected_return_gross - cost_pct
    excess_return = net_return - expected_return_hold
    threshold = safe_float(optimized.get("min_threshold_pct"), 0.5)
    decision = "REBALANCE" if excess_return > threshold else "HOLD"

    return {
        "meta": {
            "run_id": latest_summary.get("last_updated_run_id", ""),
            "timestamp": latest_summary.get("last_updated_timestamp", ""),
        },
        "returns": {
            "hold_12m": expected_return_hold,
            "gross_12m": expected_return_gross,
            "net_12m": net_return,
            "historical_annual": historical_return,
            "excess_net_12m": excess_return,
        },
        "risk": {
            "volatility_annual": expected_volatility,
            "risk_free_annual": risk_free,
            "sharpe": sharpe,
            "sharpe_source": "forward" if sharpe_forward is not None else "backtest",
            "hhi": bp.get("concentration_risk", {}).get("hhi"),
            "top5": bp.get("concentration_risk", {}).get("top_5_holdings_pct"),
        },
        "decision": {
            "verdict": decision,
            "threshold_pct": threshold,
            "intensity": safe_float(optimal.get("blend_ratio"), 0.0) * 100,
        },
        "valuation": {
            "portfolio_pe": momentum_val.get("portfolio_forward_pe"),
            "benchmark_pe": momentum_val.get("benchmark_forward_pe"),
            "dividend_yield": momentum_val.get("portfolio_dividend_yield"),
            "momentum_signal": momentum_val.get("portfolio_momentum"),
        },
        "composition": {
            "sector_exposure": bp.get("sector_exposure_list", []),
        },
    }


def _build_real_section(real_metrics: dict) -> dict:
    """Build the 'real' section of dashboard_latest.json (Mudança 3).

    Uses TWR metrics computed from the real daily series instead of
    model diagnostics from A4.
    """
    # Read portfolio history CSV for date range
    history_start = None
    history_end = None
    trading_days = 0
    if PORTFOLIO_HISTORY_CSV.exists():
        try:
            hist_df = pd.read_csv(PORTFOLIO_HISTORY_CSV, usecols=["date"])
            if not hist_df.empty:
                unique_dates = hist_df["date"].dropna().unique()
                unique_dates.sort()
                history_start = str(unique_dates[0]) if len(unique_dates) > 0 else None
                history_end = str(unique_dates[-1]) if len(unique_dates) > 0 else None
                trading_days = len(unique_dates)
        except Exception as e:
            logger.warning(f"  Could not read portfolio_history.csv: {e}")

    # Compute coverage: tracked portfolio value vs ledger total
    coverage_pct = None
    ledger_data = read_json_safe(resolve_source(LEDGER_POSITIONS_JSON))
    total_ledger_market = safe_float(ledger_data.get("total_current_market"), 0.0)
    total_ledger_invested = safe_float(ledger_data.get("total_invested_cash"), 0.0)

    if PORTFOLIO_HISTORY_CSV.exists() and total_ledger_market > 0:
        try:
            hist_df = pd.read_csv(PORTFOLIO_HISTORY_CSV)
            if not hist_df.empty:
                last_date = hist_df["date"].max()
                last_day = hist_df[hist_df["date"] == last_date]
                tracked_value = last_day["market_value"].iloc[0] if not last_day.empty else 0
                coverage_pct = round((tracked_value / total_ledger_market) * 100, 1)
        except Exception:
            pass

    # Snapshot from ledger_positions.json
    n_positions = len(ledger_data.get("positions", []))
    total_pnl = safe_float(ledger_data.get("total_unrealized_pnl"), 0.0)
    simple_roi = (total_pnl / total_ledger_invested * 100) if total_ledger_invested > 0 else 0.0

    # Structure from latest diagnostics (HHI, concentration)
    structure = {}
    diag = latest_csv_rows(DIAGNOSTICS_HISTORY_CSV)
    if not diag.empty:
        row = diag.iloc[0]
        structure = {
            "hhi": safe_float(row.get("hhi")),
            "top3": safe_float(row.get("top3_concentration")),
            "top5": safe_float(row.get("top5_concentration")),
            "n_assets": int(safe_float(row.get("n_assets"), 0)),
        }

    real: Dict[str, Any] = {
        "meta": {
            "history_start": history_start,
            "history_end": history_end,
            "trading_days": trading_days,
            "coverage_pct": coverage_pct,
            "annualize_safe": real_metrics.get("annualize_safe", False),
            "source": "portfolio_history.csv + ledger.csv",
        },
        "snapshot": {
            "total_market": round(total_ledger_market, 2),
            "total_invested": round(total_ledger_invested, 2),
            "unrealized_pnl": round(total_pnl, 2),
            "simple_roi_pct": round(simple_roi, 2),
            "n_positions": n_positions,
        },
        "twr": real_metrics.get("twr", {}),
        "benchmark": real_metrics.get("benchmark", {}),
        "cdi": real_metrics.get("cdi", {}),
        "alpha": real_metrics.get("alpha", {}),
        "relative": real_metrics.get("relative", {}),
        "structure": structure,
        "performance": real_metrics.get("performance", {}),
    }

    return real


def publish_dashboard_latest(real_metrics: dict) -> None:
    """Generate dashboard_latest.json consolidating model and real portfolio views.

    Replaces the former separate mis_model_latest.json and mis_real_latest.json.
    The 'real' section now uses TWR metrics computed from portfolio_real_daily.csv.
    """
    logger.info("Step 4c: Generating dashboard_latest.json")

    dashboard = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "model": _build_model_section(),
        "real": _build_real_section(real_metrics),
    }

    write_json(DASHBOARD_LATEST_JSON, dashboard)
    ensure_symlink(DASHBOARD_LATEST_JSON, DST)

    # Symlink history CSVs for frontend access
    ensure_symlink(PORTFOLIO_RESULTS_CSV, DST, "mis_model_history.csv")
    ensure_symlink(DIAGNOSTICS_HISTORY_CSV, DST, "mis_real_history.csv")
    ensure_symlink(ASSET_ATTRIBUTION_CSV, DST, "mis_real_attribution.csv")


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 5: GENERATE PROCESSED_NOTES.JSON COPY
# ═══════════════════════════════════════════════════════════════════════════════


def publish_processed_notes() -> None:
    """Symlink processed_notes.json if it exists in data/."""
    logger.info("Step 5: Linking processed_notes.json")
    src = SRC / "processed_notes.json"
    if src.exists():
        ensure_symlink(src, DST)
    else:
        # May still be in html/data/ from B1 (transition)
        dst = DST / "processed_notes.json"
        if dst.exists():
            logger.info("  processed_notes.json already in html/data/")
        else:
            logger.warning("  processed_notes.json not found")


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 6: SYMLINK PROGRESS FILES
# ═══════════════════════════════════════════════════════════════════════════════


def publish_progress_symlinks() -> None:
    """Ensure progress JSONs in data/ are symlinked into html/data/.

    Progress files are written live by engines during execution.
    If the canonical file in data/ doesn't exist yet, create an empty
    placeholder so the symlink target is valid.
    """
    logger.info("Step 6: Symlinking progress files")
    for name in PROGRESS_FILES:
        canonical = PROGRESS_DIR / name
        # If progress file only exists in html/data/ (transition), move it
        dst = DST / name
        if not canonical.exists() and dst.exists() and not dst.is_symlink():
            dst.rename(canonical)
            logger.info(f"  Migrated {name} → data/")
        # Create empty placeholder if needed
        if not canonical.exists():
            canonical.parent.mkdir(parents=True, exist_ok=True)
            canonical.write_text("{}", encoding="utf-8")
            logger.info(f"  Created empty {name}")
        ensure_symlink(canonical, DST)


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════


def main() -> int:
    start_time = datetime.now()
    logger.info(f"D_Publish.py v{D_PUBLISH_VERSION} — Starting frontend asset publication")
    logger.info(f"Source: {SRC}")
    logger.info(f"Target: {DST}")

    DST.mkdir(parents=True, exist_ok=True)

    try:
        # Step 0: Generate derived snapshot JSONs from history CSVs
        publish_derived_snapshots()

        # Step 1: Symlink canonical files
        publish_symlink_files()

        # Step 2: Generate scored_targets.json
        target_map = publish_scored_targets()

        # Step 3: Generate pipeline_latest.json
        publish_pipeline_latest(target_map)

        # Step 4a: Generate portfolio_real_daily.csv (Mudança 1)
        daily_df = _build_real_daily_series()

        # Step 4b: Compute real TWR metrics (Mudança 2)
        real_metrics = _compute_real_metrics(daily_df)

        # Step 4c: Generate consolidated dashboard JSON (Mudança 3)
        publish_dashboard_latest(real_metrics)

        # Step 5: Processed notes
        publish_processed_notes()

        # Step 6: Progress file symlinks
        publish_progress_symlinks()

        elapsed = (datetime.now() - start_time).total_seconds()
        logger.info(f"D_Publish.py completed in {elapsed:.1f}s")
        return 0

    except Exception as e:
        logger.critical(f"D_Publish.py failed: {e}", exc_info=True)
        return 1


if __name__ == "__main__":
    sys.exit(main())



