#!/usr/bin/env python3
"""
engines/D_Publish.py — Frontend Asset Publisher

Single point of contact between the canonical data store (data/) and the
frontend cache (html/data/).  No other engine should write to html/data/
(except progress JSONs written live during execution).

Responsibilities:
  1. Symlink canonical CSVs/JSONs from data/ → html/data/
  2. Generate derived "latest" JSON snapshots from historical CSVs
  3. Generate pipeline_latest.json (model projected onto real portfolio value)
  4. Generate scored_targets.json
  5. Generate MIS JSONs (model + real)

Usage:
    python3 engines/D_Publish.py
"""

# --- Script Version ---
D_PUBLISH_VERSION = "3.3.0"  # Add enriched history JSON (Step 8)

import csv
import json
import math
import os
import sys
import logging
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

# Ensure project root is on sys.path
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from engines.E_TWR_Monthly import compute_monthly_twr_from_daily

# ═══════════════════════════════════════════════════════════════════════════════
# PATHS — Canonical sources (data/) and targets (html/data/)
# ═══════════════════════════════════════════════════════════════════════════════

SRC = ROOT / "data"
DST = ROOT / "html" / "data"

# --- Canonical source files ---
FINDB_DIR = SRC / "findb"
STOCK_DATA_DB = FINDB_DIR / "StockDataDB.csv"
FINANCIALS_DB = FINDB_DIR / "FinancialsDB.csv"

# CDI proxy: LFTS11.SA (It Now Tesouro Selic ETF), downloaded by A1_Download
CDI_PROXY_TICKER = "LFTS11.SA"
SELIC_ANNUAL_FALLBACK = 0.1175  # Fallback if LFTS11 data unavailable

RESULTS_DIR = SRC / "results"
SCORED_STOCKS_CSV = RESULTS_DIR / "scored_stocks.csv"
SECTOR_PE_CSV = RESULTS_DIR / "sector_pe.csv"
CORRELATION_MATRIX_CSV = RESULTS_DIR / "correlation_matrix.csv"
PORTFOLIO_RESULTS_CSV = RESULTS_DIR / "portfolio_results_db.csv"
GA_FITNESS_CSV = RESULTS_DIR / "ga_fitness_noise_db.csv"
OPTIMIZED_HISTORY_JSONL = RESULTS_DIR / "optimized_portfolio_history.jsonl"
DIAGNOSTICS_HISTORY_CSV = RESULTS_DIR / "portfolio_diagnostics_history.csv"
ATTRIBUTION_HISTORY_CSV = RESULTS_DIR / "performance_attribution_history.csv"
ASSET_ATTRIBUTION_CSV = RESULTS_DIR / "asset_attribution_history.csv"
PERF_WINDOWS_CSV = RESULTS_DIR / "performance_windows_history.csv"
SCORING_PERF_CSV = RESULTS_DIR / "scoring_performance.csv"
PORTFOLIO_PERF_CSV = RESULTS_DIR / "portfolio_performance.csv"
DOWNLOAD_PERF_CSV = RESULTS_DIR / "download_performance.csv"

LEDGER_CSV = SRC / "ledger.csv"
LATEST_RUN_SUMMARY_JSON = RESULTS_DIR / "latest_run_summary.json"
OPTIMIZED_RECOMMENDATION_JSON = RESULTS_DIR / "optimized_recommendation.json"
LEDGER_POSITIONS_JSON = SRC / "ledger_positions.json"
PORTFOLIO_HISTORY_CSV = SRC / "portfolio_history.csv"
PORTFOLIO_TIMESERIES_CSV = RESULTS_DIR / "portfolio_timeseries.csv"
DIAGNOSTICS_JSON = RESULTS_DIR / "portfolio_diagnostics.json"
ATTRIBUTION_JSON = RESULTS_DIR / "performance_attribution.json"

TICKERS_FILE = ROOT / "parameters" / "tickers.txt"

# --- New: Real daily returns CSV (Mudança 1) ---
PORTFOLIO_REAL_DAILY_CSV = RESULTS_DIR / "portfolio_real_daily.csv"


# --- Derived files (generated by D_Publish, stored in data/results/) ---
DERIVED_DIR = RESULTS_DIR
SCORED_TARGETS_JSON = DERIVED_DIR / "scored_targets.json"
PIPELINE_LATEST_JSON = DERIVED_DIR / "pipeline_latest.json"
DASHBOARD_LATEST_JSON = DERIVED_DIR / "dashboard_latest.json"

# --- Progress files (written live by engines, canonical in data/) ---
PROGRESS_DIR = SRC
PROGRESS_FILES = [
    "pipeline_progress.json",
    "download_progress.json",
    "scoring_progress.json",
    "portfolio_progress.json",
]

# Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - D_Publish - %(levelname)s - %(message)s",
)
logger = logging.getLogger("D_Publish")


# ═══════════════════════════════════════════════════════════════════════════════
# UTILITIES
# ═══════════════════════════════════════════════════════════════════════════════


def safe_float(v: Any, default: float = 0.0) -> float:
    """Safely convert a value to float."""
    if v is None or v == "":
        return default
    try:
        return float(v)
    except (TypeError, ValueError):
        return default


def sanitize_for_json(value: Any) -> Any:
    """Replace NaN/Inf with None for JSON serialization."""
    if isinstance(value, dict):
        return {k: sanitize_for_json(v) for k, v in value.items()}
    if isinstance(value, list):
        return [sanitize_for_json(v) for v in value]
    if isinstance(value, float):
        if not math.isfinite(value):
            return None
    return value


def write_json(path: Path, payload: dict) -> None:
    """Write JSON with NaN sanitization."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(sanitize_for_json(payload), f, indent=2, ensure_ascii=False, allow_nan=False)
    logger.info(f"  Wrote {path.name}")


def ensure_symlink(src: Path, dst_dir: Path, dst_name: Optional[str] = None) -> bool:
    """Create a symlink in dst_dir pointing to src.  Returns True on success.

    If the destination already exists:
      - If it's a symlink pointing to src → no-op
      - If it's a symlink pointing elsewhere → replace
      - If it's a regular file → remove and replace with symlink
    Uses *absolute* paths so the link works regardless of cwd.
    """
    if not src.exists():
        logger.warning(f"  Source not found, skipping: {src.name}")
        return False

    src_abs = src.resolve()
    dst = dst_dir / (dst_name or src.name)
    dst.parent.mkdir(parents=True, exist_ok=True)

    # Already a correct symlink?
    if dst.is_symlink():
        try:
            if dst.resolve() == src_abs:
                logger.info(f"  {dst.name} ✓ symlink OK")
                return True
        except OSError:
            pass
        # Wrong target — remove and recreate
        dst.unlink()

    # Regular file occupying the slot — remove it
    if dst.exists():
        dst.unlink()

    os.symlink(src_abs, dst)
    logger.info(f"  {dst.name} → {src_abs}")
    return True


def read_json_safe(path: Path) -> dict:
    """Read a JSON file, returning empty dict if missing or corrupt."""
    if not path.exists():
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        logger.warning(f"  Could not read {path.name}: {e}")
        return {}


def latest_csv_rows(path: Path, run_id_col: str = "run_id") -> pd.DataFrame:
    """Read a CSV and return only rows from the latest run_id."""
    if not path.exists():
        return pd.DataFrame()
    try:
        df = pd.read_csv(path)
        if run_id_col not in df.columns or df.empty:
            return df
        latest = df[run_id_col].max()
        return df[df[run_id_col] == latest].copy()
    except Exception as e:
        logger.warning(f"  Could not read {path.name}: {e}")
        return pd.DataFrame()


def normalize_ticker(s: Optional[str]) -> str:
    """Normalize string for ticker matching (uppercase, alphanum only)."""
    if not s:
        return ""
    return "".join(c for c in str(s).upper() if c.isalnum())


def _load_financials() -> pd.DataFrame:
    """Load latest financials from FinancialsDB."""
    if not FINANCIALS_DB.exists():
        return pd.DataFrame()
    try:
        df = pd.read_csv(FINANCIALS_DB)
        df['Stock_norm'] = df['Stock'].apply(normalize_ticker)
        # Keep latest for each stock if duplicates exist
        if 'LastUpdated' in df.columns:
            df['LastUpdated'] = pd.to_datetime(df['LastUpdated'], errors='coerce')
            df = df.sort_values('LastUpdated').drop_duplicates('Stock_norm', keep='last')
        return df.set_index('Stock_norm')
    except Exception as e:
        logger.warning(f"Could not load financials: {e}")
        return pd.DataFrame()


def _calculate_weighted_metrics(weights: Dict[str, float], financials: pd.DataFrame) -> Dict[str, Any]:
    """Calculate weighted P/E and Liquidity for a portfolio."""
    if financials.empty or not weights:
        return {"pe": None, "liquidity": None}

    total_w = sum(weights.values())
    if total_w == 0:
        return {"pe": None, "liquidity": None}

    weighted_pe = 0.0
    pe_weight_sum = 0.0
    weighted_liq = 0.0

    for ticker, w in weights.items():
        norm = normalize_ticker(ticker)
        if norm in financials.index:
            row = financials.loc[norm]
            pe = safe_float(row.get('forwardPE'), None)
            liq = safe_float(row.get('averageVolume'), 0.0)

            if pe is not None and pe > 0:
                weighted_pe += pe * w
                pe_weight_sum += w

            weighted_liq += liq * w

    return {
        "pe": weighted_pe / pe_weight_sum if pe_weight_sum > 0 else None,
        "liquidity": weighted_liq / total_w
    }


def _calculate_avg_internal_corr(tickers: List[str]) -> Optional[float]:
    """Calculate average internal correlation from correlation_matrix.csv."""
    if not CORRELATION_MATRIX_CSV.exists() or len(tickers) < 2:
        return None
    try:
        df = pd.read_csv(CORRELATION_MATRIX_CSV).set_index('Stock')
        # Use only unique normalized tickers
        norms = list(dict.fromkeys(normalize_ticker(t) for t in tickers if t))
        # Map tickers to columns/index in the matrix (which use exact Stock names)
        matrix_tickers = {normalize_ticker(idx): idx for idx in df.index}
        valid_tickers = [matrix_tickers[n] for n in norms if n in matrix_tickers]

        if len(valid_tickers) < 2:
            return None

        subset = df.loc[valid_tickers, valid_tickers]
        # Get upper triangle excluding diagonal
        vals = []
        for i in range(len(valid_tickers)):
            for j in range(i + 1, len(valid_tickers)):
                val = safe_float(subset.iloc[i, j], None)
                if val is not None:
                    vals.append(val)

        return float(np.mean(vals)) if vals else None
    except Exception as e:
        logger.warning(f"Could not calculate internal correlation: {e}")
        return None


def resolve_source(canonical: Path, fallback_name: Optional[str] = None) -> Path:
    """Return canonical path if it exists, otherwise fall back to html/data/.

    During the transition period some files may only exist in html/data/ because
    the pipeline hasn't been fully re-run yet.  This helper transparently picks
    whichever copy is available (preferring canonical).
    """
    if canonical.exists():
        return canonical
    fb = DST / (fallback_name or canonical.name)
    if fb.exists():
        logger.debug(f"  Fallback: using {fb} (canonical {canonical} not yet created)")
        return fb
    return canonical  # caller will handle missing file


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 0: GENERATE DERIVED SNAPSHOT JSONs FROM HISTORY CSVs
# ═══════════════════════════════════════════════════════════════════════════════


def publish_derived_snapshots() -> None:
    """Generate snapshot JSONs from the latest row of their history CSVs.

    These files used to be written directly by A4_Analysis.py.  Now A4 only
    appends to the history CSVs and D_Publish derives the snapshot JSONs,
    eliminating the duplication.

    Generated files (in data/results/):
      - portfolio_diagnostics.json   ← from portfolio_diagnostics_history.csv
      - performance_attribution.json ← from performance_attribution_history.csv
    """
    logger.info("Step 0: Generating derived snapshot JSONs from history CSVs")

    # --- portfolio_diagnostics.json ---
    diag = latest_csv_rows(DIAGNOSTICS_HISTORY_CSV)
    if not diag.empty:
        row = diag.iloc[0]
        payload = {k: (None if pd.isna(v) else v) for k, v in row.to_dict().items()}
        write_json(DIAGNOSTICS_JSON, payload)
        ensure_symlink(DIAGNOSTICS_JSON, DST)
    else:
        logger.warning("  No diagnostics history data — skipping portfolio_diagnostics.json")

    # --- performance_attribution.json ---
    attr = latest_csv_rows(ATTRIBUTION_HISTORY_CSV)
    if not attr.empty:
        row = attr.iloc[0]
        payload = {k: (None if pd.isna(v) else v) for k, v in row.to_dict().items()}
        write_json(ATTRIBUTION_JSON, payload)
        ensure_symlink(ATTRIBUTION_JSON, DST)
    else:
        logger.warning("  No attribution history data — skipping performance_attribution.json")


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 1: COPY CANONICAL FILES
# ═══════════════════════════════════════════════════════════════════════════════


def publish_symlink_files() -> None:
    """Create symlinks in html/data/ pointing to canonical files in data/."""
    logger.info("Step 1: Symlinking canonical files to html/data/")

    # CSVs from data/results/
    ensure_symlink(SCORED_STOCKS_CSV, DST)
    ensure_symlink(SECTOR_PE_CSV, DST)
    ensure_symlink(CORRELATION_MATRIX_CSV, DST)
    ensure_symlink(PORTFOLIO_RESULTS_CSV, DST)  # also exposed as mis_model_history.csv (Step 4)
    ensure_symlink(GA_FITNESS_CSV, DST)
    ensure_symlink(SCORING_PERF_CSV, DST)
    ensure_symlink(PORTFOLIO_PERF_CSV, DST)
    ensure_symlink(DOWNLOAD_PERF_CSV, DST)

    # StockDataDB
    ensure_symlink(STOCK_DATA_DB, DST)

    # Ledger CSV
    ensure_symlink(LEDGER_CSV, DST)

    # Tickers file
    ensure_symlink(TICKERS_FILE, DST)

    # JSONs — use resolve_source to fallback to html/data/ during transition
    # Note: DIAGNOSTICS_JSON and ATTRIBUTION_JSON are generated by
    # publish_derived_snapshots() and symlinked there.
    for json_src in [LATEST_RUN_SUMMARY_JSON, OPTIMIZED_RECOMMENDATION_JSON,
                     LEDGER_POSITIONS_JSON]:
        resolved = resolve_source(json_src)
        # Only symlink if the resolved source is outside html/data/
        if resolved.parent != DST:
            ensure_symlink(resolved, DST, json_src.name)

    # Portfolio history CSV (migrated from JSON in Phase 3.3)
    ensure_symlink(PORTFOLIO_HISTORY_CSV, DST)

    # Portfolio timeseries
    resolved_ts = resolve_source(PORTFOLIO_TIMESERIES_CSV)
    if resolved_ts.parent != DST:
        ensure_symlink(resolved_ts, DST, PORTFOLIO_TIMESERIES_CSV.name)


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 2: GENERATE SCORED_TARGETS.JSON
# ═══════════════════════════════════════════════════════════════════════════════


def publish_scored_targets() -> Dict[str, float]:
    """Generate scored_targets.json from latest scored_stocks.csv run."""
    logger.info("Step 2: Generating scored_targets.json")

    targets: Dict[str, float] = {}
    symbols: Dict[str, str] = {}

    # Latest close prices used to sanity-check target prices (cap upside to 1000% → 11x)
    price_map = _load_latest_prices()

    latest = latest_csv_rows(SCORED_STOCKS_CSV)
    if latest.empty:
        logger.warning("  No scored stocks data available")
        write_json(SCORED_TARGETS_JSON, {
            "targets": {},
            "symbols": {},
            "generated_at": datetime.now(timezone.utc).isoformat(),
        })
        ensure_symlink(SCORED_TARGETS_JSON, DST)
        return targets

    for _, row in latest.iterrows():
        stock = str(row.get("Stock", "")).strip()
        if not stock:
            continue
        tp = safe_float(row.get("TargetPrice"), 0.0)
        if tp <= 0:
            continue

        # Cap unrealistic targets if they imply >1000% upside relative to latest close
        price = price_map.get(stock)
        if price is None:
            # try normalized lookup
            norm = normalize_ticker(stock)
            for k, v in price_map.items():
                if normalize_ticker(k) == norm:
                    price = v
                    break
        if price and price > 0:
            max_target = price * 11  # 1000% upside cap (UpsidePotential <= 10)
            if tp > max_target:
                logger.warning(
                    f"  Skipping target for {stock}: {tp:.2f} > cap {max_target:.2f} (price {price:.2f})"
                )
                continue

        key = normalize_ticker(stock)
        targets[key] = tp
        symbols[key] = stock

    write_json(SCORED_TARGETS_JSON, {
        "targets": targets,
        "symbols": symbols,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    })
    ensure_symlink(SCORED_TARGETS_JSON, DST)
    return targets


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 3: GENERATE PIPELINE_LATEST.JSON
# ═══════════════════════════════════════════════════════════════════════════════


def _load_latest_prices() -> Dict[str, float]:
    """Stream StockDataDB.csv and keep last close price per symbol."""
    result: Dict[str, float] = {}
    if not STOCK_DATA_DB.exists():
        return result
    try:
        with open(STOCK_DATA_DB, encoding="utf-8", errors="replace") as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                stock = (row.get("Stock") or "").strip()
                close_str = (row.get("Close") or "").strip()
                if stock and close_str:
                    try:
                        result[stock] = float(close_str)
                    except ValueError:
                        pass
    except Exception as e:
        logger.warning(f"  Could not load prices: {e}")
    return result


def _load_findb_target_prices() -> Dict[str, float]:
    """Read the latest targetMeanPrice per stock from FinancialsDB.csv.

    Used as a fallback for stocks that were filtered out of scored_stocks.csv
    (e.g. PETR3 when its target is below current price → negative upside → excluded
    from scoring but still present in the model portfolio).
    Returns a dict keyed by normalize_ticker(stock).
    """
    result: Dict[str, float] = {}
    findb = SRC / "findb" / "FinancialsDB.csv"
    if not findb.exists():
        return result
    try:
        df = pd.read_csv(findb)
        df["LastUpdated"] = pd.to_datetime(df["LastUpdated"], errors="coerce")
        latest = df.sort_values("LastUpdated").drop_duplicates(subset="Stock", keep="last")
        for _, row in latest.iterrows():
            tp = safe_float(row.get("targetMeanPrice"), 0.0)
            if tp > 0:
                result[normalize_ticker(str(row.get("Stock", "")))] = tp
    except Exception as e:
        logger.warning(f"  Could not load targetMeanPrice from FinancialsDB: {e}")
    return result


def _load_broker_name_mapping() -> Dict[str, str]:
    """Load BrokerName → Ticker mapping from tickers.txt."""
    mapping: Dict[str, str] = {}
    if not TICKERS_FILE.exists():
        return mapping
    try:
        with open(TICKERS_FILE, encoding="utf-8") as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                ticker = (row.get("Ticker") or "").strip()
                broker_name = (row.get("BrokerName") or "").strip()
                name = (row.get("Name") or "").strip()
                if ticker:
                    base = ticker.replace(".SA", "").strip()
                    mapping[normalize_ticker(base)] = ticker
                    if broker_name:
                        mapping[normalize_ticker(broker_name)] = ticker
                    if name:
                        mapping[normalize_ticker(name)] = ticker
    except Exception as e:
        logger.warning(f"  Could not load tickers mapping: {e}")
    return mapping


def _load_scored_stocks_meta() -> Dict[str, Dict[str, Any]]:
    """Load metadata from scored_stocks.csv for enrichment."""
    meta = {}
    if SCORED_STOCKS_CSV.exists():
        try:
            df = pd.read_csv(SCORED_STOCKS_CSV)
            for _, row in df.iterrows():
                ticker = normalize_ticker(str(row.get("Stock", "")))
                meta[ticker] = {
                    "composite_score": safe_float(row.get("CompositeScore")),
                    "momentum_score": safe_float(row.get("Momentum")),
                    "upside_pct": safe_float(row.get("PotentialUpside_pct")),
                    "annual_ret": safe_float(row.get("AnnualizedMeanReturn")),
                    "annual_vol": safe_float(row.get("AnnualizedStdDev")),
                }
        except Exception as e:
            logger.warning(f"  Could not load scored_stocks meta: {e}")
    return meta


def publish_pipeline_latest(target_map: Dict[str, float]) -> None:
    """Generate pipeline_latest.json: model portfolio projected onto real values."""
    logger.info("Step 3: Generating pipeline_latest.json")

    # Load latest_run_summary.json for model stocks/weights
    summary = read_json_safe(resolve_source(LATEST_RUN_SUMMARY_JSON))
    bp = summary.get("best_portfolio_details", {})
    stocks = bp.get("stocks", [])
    weights = bp.get("weights", [])

    if not stocks:
        # Fallback: try portfolio_results_db.csv
        if PORTFOLIO_RESULTS_CSV.exists():
            try:
                df = pd.read_csv(PORTFOLIO_RESULTS_CSV)
                if not df.empty:
                    last_row = df.iloc[-1]
                    stocks_str = str(last_row.get("stocks", ""))
                    weights_str = str(last_row.get("weights", ""))
                    stocks = [s.strip() for s in stocks_str.split(",") if s.strip()]
                    weights = [safe_float(w) for w in weights_str.split(",") if w.strip()]
            except Exception:
                pass

    if not stocks:
        write_json(PIPELINE_LATEST_JSON, {
            "stocks": [], "weights": [], "rows": [], "totals": {},
            "generated_at": datetime.now(timezone.utc).isoformat(),
        })
        ensure_symlink(PIPELINE_LATEST_JSON, DST)
        return

    # Normalize weights to percentages if they look like fractions
    if weights:
        s = sum(weights)
        if 0 < s <= 1.1:
            weights = [w * 100.0 for w in weights]

    # Get available capital from ledger_positions.json
    ledger_data = read_json_safe(resolve_source(LEDGER_POSITIONS_JSON))
    total_market = safe_float(ledger_data.get("total_current_market"), 0.0)
    total_invested = safe_float(ledger_data.get("total_invested_cash"), 0.0)
    available_capital = total_market if total_market > 0 else total_invested

    # Load prices
    price_map = _load_latest_prices()
    # Fallback target prices from FinancialsDB (covers stocks filtered out of scoring,
    # e.g. those with negative upside like PETR3 when target < current price)
    findb_targets = _load_findb_target_prices()
    # Enrichment: Scored stocks meta (scores, momentum, performance)
    scored_meta = _load_scored_stocks_meta()

    # Build rows
    rows = []
    totals = {
        "totalPct": 0.0,
        "totalCurrentSum": 0.0,
        "totalProjectedQty": 0,
        "totalProjectedInvested": 0.0,
        "totalProjectedBRL": 0.0,
    }

    for i, stock in enumerate(stocks):
        w = safe_float(weights[i] if i < len(weights) else 0)
        totals["totalPct"] += w

        allocated = (available_capital * (w / 100.0)) if available_capital > 0 else None

        # Find current price
        norm = normalize_ticker(stock)
        current = price_map.get(stock)
        if current is None:
            for k, v in price_map.items():
                if normalize_ticker(k) == norm:
                    current = v
                    break

        # Find target price: prefer scored_targets (upside > 0), fall back to FinancialsDB
        tp = target_map.get(norm) or findb_targets.get(norm)

        # Calculate projections
        projected_qty = None
        projected_invested = None
        projected_brl = None

        if allocated is not None and current and current > 0:
            projected_qty = int(math.floor(allocated / current))
            projected_invested = projected_qty * current
        if projected_qty is not None and tp:
            projected_brl = projected_qty * tp

        if allocated:
            totals["totalCurrentSum"] += allocated
        if projected_qty:
            totals["totalProjectedQty"] += projected_qty
        if projected_invested:
            totals["totalProjectedInvested"] += projected_invested
        if projected_brl:
            totals["totalProjectedBRL"] += projected_brl

        # Find enrichment data
        meta = scored_meta.get(norm, {})

        rows.append({
            "ticker": stock,
            "weight": w,
            "current": current,
            "projectedQty": projected_qty,
            "projectedInvested": projected_invested,
            "target": tp,
            "projectedBRL": projected_brl,
            # Enriched fields
            "composite_score": meta.get("composite_score"),
            "momentum_score": meta.get("momentum_score"),
            "upside_pct": meta.get("upside_pct"),
            "annual_ret": meta.get("annual_ret"),
            "annual_vol": meta.get("annual_vol"),
        })

    rows.sort(key=lambda r: (r.get("projectedInvested") or 0), reverse=True)

    write_json(PIPELINE_LATEST_JSON, {
        "stocks": stocks,
        "weights": weights,
        "rows": rows,
        "totals": totals,
        "used_path": str(LATEST_RUN_SUMMARY_JSON),
        "generated_at": datetime.now(timezone.utc).isoformat(),
    })
    ensure_symlink(PIPELINE_LATEST_JSON, DST)


# ═══════════════════════════════════════════════════════════════════════════════
# CDI DAILY RETURNS LOADER
# ═══════════════════════════════════════════════════════════════════════════════


def _load_cdi_daily_returns() -> Tuple[Dict[str, float], str]:
    """Load real CDI daily returns from LFTS11.SA in StockDataDB.csv.

    Returns:
        (dict mapping date_str → daily_return, source_label)
    Falls back to SELIC synthetic flat rate if LFTS11 data is unavailable.
    """
    cdi_by_date: Dict[str, float] = {}
    source = "SELIC flat rate (fallback)"

    if STOCK_DATA_DB.exists():
        try:
            df = pd.read_csv(STOCK_DATA_DB)
            cdi_df = df[df["Stock"] == CDI_PROXY_TICKER].copy()
            if not cdi_df.empty:
                cdi_df["Date"] = pd.to_datetime(cdi_df["Date"], errors="coerce")
                cdi_df = cdi_df.dropna(subset=["Date"]).sort_values("Date")
                cdi_df["daily_return"] = cdi_df["Close"].pct_change()
                for _, row in cdi_df.iterrows():
                    dt = row["Date"].strftime("%Y-%m-%d")
                    dr = row["daily_return"]
                    if pd.notna(dr):
                        cdi_by_date[dt] = float(dr)
                source = f"{CDI_PROXY_TICKER} (real)"
                logger.info(f"  Loaded {len(cdi_by_date)} CDI daily returns from {CDI_PROXY_TICKER}")
        except Exception as e:
            logger.warning(f"  Could not load CDI data from StockDataDB: {e}")

    if not cdi_by_date:
        logger.warning(f"  {CDI_PROXY_TICKER} not found in StockDataDB — using SELIC flat rate fallback")

    return cdi_by_date, source


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 4a: GENERATE PORTFOLIO_REAL_DAILY.CSV (Mudança 1)
# ═══════════════════════════════════════════════════════════════════════════════


def _build_real_daily_series() -> pd.DataFrame:
    """Build the real daily returns CSV from portfolio_history + ledger + timeseries.

    Output columns: date, portfolio_value, cost_basis, cash_flow,
                    portfolio_return, benchmark_return, cdi_return

    Returns an empty DataFrame if source data is insufficient.
    """
    logger.info("Step 4a: Building portfolio_real_daily.csv")

    # --- Load portfolio_history.csv → {date: portfolio_value, cost_basis} ---
    if not PORTFOLIO_HISTORY_CSV.exists():
        logger.warning("  portfolio_history.csv not found — skipping real daily series")
        return pd.DataFrame()

    hist = pd.read_csv(PORTFOLIO_HISTORY_CSV)
    if hist.empty:
        return pd.DataFrame()

    # Group by date → one row per date (market_value & cost_basis are already totals)
    hist_daily = hist.groupby("date").agg(
        portfolio_value=("market_value", "first"),
        cost_basis=("cost_basis", "first"),
    ).reset_index().sort_values("date")

    # --- Load ledger.csv → cash flows by date ---
    cf_by_date: Dict[str, float] = {}
    if LEDGER_CSV.exists():
        ledger = pd.read_csv(LEDGER_CSV)
        for _, row in ledger.iterrows():
            dt = str(row.get("trade_date", "")).strip()[:10]
            side = str(row.get("side", "")).upper()
            total_cost = safe_float(row.get("total_cost"), 0.0)
            # BUY = cash out (positive CF into portfolio), SELL = cash in (negative)
            cf = total_cost if side == "BUY" else -total_cost
            cf_by_date[dt] = cf_by_date.get(dt, 0.0) + cf

    # --- Load portfolio_timeseries.csv → benchmark daily returns ---
    bench_by_date: Dict[str, float] = {}
    ts_path = resolve_source(PORTFOLIO_TIMESERIES_CSV)
    if ts_path.exists():
        ts = pd.read_csv(ts_path)
        for _, row in ts.iterrows():
            dt = str(row.get("date", "")).strip()[:10]
            br = safe_float(row.get("benchmark1_daily_return"), None)
            if br is not None:
                bench_by_date[dt] = br

    # --- Load CDI daily returns (real from LFTS11 or SELIC fallback) ---
    cdi_by_date, cdi_source = _load_cdi_daily_returns()
    cdi_is_synthetic = "fallback" in cdi_source
    selic_daily_fallback = (1 + SELIC_ANNUAL_FALLBACK) ** (1 / 252) - 1

    # --- Build daily series (only dates present in portfolio_history, already business-days) ---
    dates = hist_daily["date"].tolist()
    rows = []

    for i, dt in enumerate(dates):
        pv = hist_daily.iloc[i]["portfolio_value"]
        cb = hist_daily.iloc[i]["cost_basis"]
        cf = cf_by_date.get(dt, 0.0)

        if i == 0:
            port_ret = None
            bench_ret = None
            cdi_ret = None
        else:
            prev_pv = hist_daily.iloc[i - 1]["portfolio_value"]
            prev_cb = hist_daily.iloc[i - 1]["cost_basis"]

            # Determine actual cash flow for TWR calculation
            # If cost_basis changed, there was a real transaction
            cost_delta = cb - prev_cb
            if abs(cost_delta) > 0.01:
                # Use cost_basis delta as cash flow (more reliable than ledger
                # because it's already aligned with the tracked portfolio)
                effective_cf = cost_delta
            else:
                effective_cf = 0.0

            # TWR daily return: r = (V_t - CF_t) / V_{t-1} - 1
            if prev_pv > 0:
                port_ret = (pv - effective_cf) / prev_pv - 1
            else:
                port_ret = None

            bench_ret = bench_by_date.get(dt, None)

            # CDI: real data from LFTS11, fallback to synthetic
            cdi_ret = cdi_by_date.get(dt, selic_daily_fallback if cdi_is_synthetic else None)

        rows.append({
            "date": dt,
            "portfolio_value": round(pv, 2),
            "cost_basis": round(cb, 2),
            "cash_flow": round(cf, 2),
            "portfolio_return": round(port_ret, 8) if port_ret is not None else "",
            "benchmark_return": round(bench_ret, 8) if bench_ret is not None else "",
            "cdi_return": round(cdi_ret, 8) if cdi_ret is not None else "",
        })

    df = pd.DataFrame(rows)
    if not df.empty:
        df.to_csv(PORTFOLIO_REAL_DAILY_CSV, index=False)
        logger.info(f"  Wrote {PORTFOLIO_REAL_DAILY_CSV.name} ({len(df)} rows)")
        ensure_symlink(PORTFOLIO_REAL_DAILY_CSV, DST)

    return df


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 4b: COMPUTE REAL TWR METRICS (Mudança 2)
# ═══════════════════════════════════════════════════════════════════════════════


def _compute_real_metrics(daily_df: pd.DataFrame) -> dict:
    """Compute TWR-based metrics from the real daily series.

    Returns a dict with twr, benchmark, alpha, and relative sub-dicts.
    """
    if daily_df.empty:
        return {}

    # Extract return series (skip first row which has no return)
    port_rets = pd.to_numeric(daily_df["portfolio_return"], errors="coerce").dropna()
    bench_rets = pd.to_numeric(daily_df["benchmark_return"], errors="coerce").dropna()

    if port_rets.empty:
        return {}

    n = len(port_rets)

    # --- CDI metrics (real data from LFTS11 or SELIC fallback) ---
    # Computed first so we can use actual CDI annual rate as risk-free
    cdi_rets = pd.to_numeric(daily_df["cdi_return"], errors="coerce").dropna()
    if not cdi_rets.empty:
        cdi_total = float(np.prod(1 + cdi_rets.values) - 1)
        cdi_annual = float((1 + cdi_total) ** (252 / len(cdi_rets)) - 1) if len(cdi_rets) > 0 else SELIC_ANNUAL_FALLBACK
        cdi_source = CDI_PROXY_TICKER
    else:
        cdi_daily_fb = (1 + SELIC_ANNUAL_FALLBACK) ** (1 / 252) - 1
        cdi_total = (1 + cdi_daily_fb) ** n - 1
        cdi_annual = SELIC_ANNUAL_FALLBACK
        cdi_source = "SELIC flat rate (fallback)"

    risk_free_annual = cdi_annual  # Use real CDI rate as risk-free

    # --- Portfolio TWR metrics ---
    total_return = float(np.prod(1 + port_rets.values) - 1)
    annual_return = float((1 + total_return) ** (252 / n) - 1) if n > 0 else 0.0
    volatility = float(port_rets.std(ddof=1) * np.sqrt(252)) if n > 1 else 0.0
    sharpe = float((annual_return - risk_free_annual) / volatility) if volatility > 0 else None
    
    # Sortino
    downside = port_rets[port_rets < 0]
    downside_dev = float(downside.std(ddof=1) * np.sqrt(252)) if len(downside) > 1 else 0.0
    sortino = float((annual_return - risk_free_annual) / downside_dev) if downside_dev > 0 else None

    # Max drawdown (compute from TWR index)
    idx = np.cumprod(1 + port_rets.values)
    peak = np.maximum.accumulate(idx)
    dd = (idx - peak) / peak
    max_drawdown = float(abs(dd.min())) if len(dd) > 0 else 0.0

    # Calmar
    calmar = float(annual_return / max_drawdown) if max_drawdown > 0 else None

    # --- Benchmark metrics (same dates) ---
    # Align benchmark to same index as portfolio returns
    common_idx = port_rets.index.intersection(bench_rets.index)
    port_common = port_rets.loc[common_idx]
    bench_common = bench_rets.loc[common_idx]

    bench_total = float(np.prod(1 + bench_common.values) - 1) if len(bench_common) > 0 else 0.0
    n_bench = len(bench_common)
    bench_annual = float((1 + bench_total) ** (252 / n_bench) - 1) if n_bench > 0 else 0.0

    # --- Alpha ---
    alpha_total = total_return - bench_total
    alpha_annual = annual_return - bench_annual

    # --- Relative metrics ---
    beta = None
    tracking_error = None
    information_ratio = None
    correlation = None

    if len(port_common) > 1 and bench_common.std() > 0:
        cov_matrix = np.cov(port_common.values, bench_common.values)
        beta = float(cov_matrix[0, 1] / cov_matrix[1, 1])

        diff = port_common.values - bench_common.values
        tracking_error = float(np.std(diff, ddof=1) * np.sqrt(252))
        if tracking_error > 0:
            information_ratio = float(alpha_annual / tracking_error)

        corr_val = np.corrcoef(port_common.values, bench_common.values)[0, 1]
        correlation = float(corr_val) if np.isfinite(corr_val) else None

    # % do CDI: standard Brazilian fund metric
    pct_cdi = round((total_return / cdi_total) * 100, 1) if cdi_total > 0 else None

    # Annualization safety flag: annualized numbers are unreliable under 1 year
    annualize_safe = n >= 252

    # --- Performance windows ---
    performance = _compute_performance_windows(daily_df)

    return {
        "twr": {
            "total_return": round(total_return, 4),
            "annual_return": round(annual_return, 4),
            "volatility": round(volatility, 4),
            "sharpe": round(sharpe, 2) if sharpe is not None else None,
            "sortino": round(sortino, 2) if sortino is not None else None,
            "max_drawdown": round(max_drawdown, 4),
            "calmar": round(calmar, 2) if calmar is not None else None,
            "pct_cdi": pct_cdi,
            "risk_free_annual": round(risk_free_annual, 4),
        },
        "benchmark": {
            "ticker": "^BVSP",
            "total_return": round(bench_total, 4),
            "annual_return": round(bench_annual, 4),
        },
        "cdi": {
            "total_return": round(cdi_total, 4),
            "annual_rate": round(cdi_annual, 4),
            "source": cdi_source,
        },
        "alpha": {
            "total": round(alpha_total, 4),
            "annual": round(alpha_annual, 4),
        },
        "relative": {
            "beta": round(beta, 2) if beta is not None else None,
            "tracking_error": round(tracking_error, 4) if tracking_error is not None else None,
            "information_ratio": round(information_ratio, 2) if information_ratio is not None else None,
            "correlation": round(correlation, 2) if correlation is not None else None,
        },
        "annualize_safe": annualize_safe,
        "performance": performance,
    }


def _compute_performance_windows(daily_df: pd.DataFrame) -> dict:
    """Compute portfolio, benchmark & CDI returns for standard time windows.

    Windows: YTD, 3M, 6M, 12M, 24M — computed from the real daily series.
    Each window includes portfolio, benchmark, cdi, and pct_cdi.
    """
    if daily_df.empty:
        return {}

    df = daily_df.copy()
    df["date_dt"] = pd.to_datetime(df["date"])
    df["port_r"] = pd.to_numeric(df["portfolio_return"], errors="coerce")
    df["bench_r"] = pd.to_numeric(df["benchmark_return"], errors="coerce")
    df["cdi_r"] = pd.to_numeric(df["cdi_return"], errors="coerce")

    last_date = df["date_dt"].max()
    result = {}


    windows = {
        "YTD": pd.Timestamp(last_date.year, 1, 1),
        "3M": last_date - pd.DateOffset(months=3),
        "6M": last_date - pd.DateOffset(months=6),
        "12M": last_date - pd.DateOffset(months=12),
        "24M": last_date - pd.DateOffset(months=24),
    }

    for label, start in windows.items():
        subset = df[df["date_dt"] >= start]
        port_r = subset["port_r"].dropna()
        bench_r = subset["bench_r"].dropna()
        cdi_r = subset["cdi_r"].dropna()

        if port_r.empty:
            continue

        p_total = float(np.prod(1 + port_r.values) - 1)
        b_total = float(np.prod(1 + bench_r.values) - 1) if not bench_r.empty else None
        c_total = float(np.prod(1 + cdi_r.values) - 1) if not cdi_r.empty else None
        pct_cdi = round((p_total / c_total) * 100, 1) if c_total and c_total > 0 else None

        result[label] = {
            "portfolio": round(p_total, 4),
            "benchmark": round(b_total, 4) if b_total is not None else None,
            "cdi": round(c_total, 4),
            "pct_cdi": pct_cdi,
        }

    return result



def _compute_risk_windows(daily_df: pd.DataFrame, hist_df: pd.DataFrame) -> dict:
    """Compute Tracking Error, Information Ratio, and HHI per time window.

    Windows: All, YTD, 3M, 6M, 12M, 24M.
    TE and IR are derived from daily returns in daily_df.
    HHI is a point-in-time snapshot from the last date in hist_df within each window.
    """
    if daily_df.empty:
        return {}

    df = daily_df.copy()
    df["date_dt"] = pd.to_datetime(df["date"])
    df["port_r"] = pd.to_numeric(df["portfolio_return"], errors="coerce")
    df["bench_r"] = pd.to_numeric(df["benchmark_return"], errors="coerce")

    last_date = df["date_dt"].max()

    # Prepare hist_df for HHI lookups
    hist_has_data = hist_df is not None and not hist_df.empty
    if hist_has_data:
        hist_df = hist_df.copy()
        hist_df["date_dt"] = pd.to_datetime(hist_df["date"])
        hist_df["value_f"] = pd.to_numeric(hist_df["value"], errors="coerce")

    windows = {
        "All": df["date_dt"].min(),
        "YTD": pd.Timestamp(last_date.year, 1, 1),
        "3M": last_date - pd.DateOffset(months=3),
        "6M": last_date - pd.DateOffset(months=6),
        "12M": last_date - pd.DateOffset(months=12),
        "24M": last_date - pd.DateOffset(months=24),
    }

    result = {}

    for label, start in windows.items():
        subset = df[df["date_dt"] >= start]
        port_r = subset["port_r"].dropna()
        bench_r = subset["bench_r"].dropna()

        if len(port_r) < 2 or len(bench_r) < 2:
            continue

        # Align to common dates
        common_idx = port_r.index.intersection(bench_r.index)
        port_common = port_r.loc[common_idx]
        bench_common = bench_r.loc[common_idx]
        n = len(port_common)

        if n < 2:
            continue

        # Tracking Error
        diff = port_common.values - bench_common.values
        te = float(np.std(diff, ddof=1) * np.sqrt(252))

        # Alpha annual
        port_total = float(np.prod(1 + port_common.values) - 1)
        bench_total = float(np.prod(1 + bench_common.values) - 1)
        port_annual = float((1 + port_total) ** (252 / n) - 1) if n > 0 else 0.0
        bench_annual = float((1 + bench_total) ** (252 / n) - 1) if n > 0 else 0.0
        alpha_annual = port_annual - bench_annual

        # Information Ratio
        ir = float(alpha_annual / te) if te > 0 else None

        # HHI: point-in-time from last date in hist_df within this window
        hhi = None
        n_assets = None
        if hist_has_data:
            hist_window = hist_df[hist_df["date_dt"] >= start]
            if not hist_window.empty:
                last_hist_date = hist_window["date_dt"].max()
                last_day = hist_window[hist_window["date_dt"] == last_hist_date]
                values = last_day["value_f"].dropna()
                total_val = values.sum()
                if total_val > 0:
                    w = values / total_val
                    hhi = round(float((w ** 2).sum()), 4)
                    n_assets = int((values > 0).sum())

        entry: Dict[str, Any] = {
            "tracking_error": round(te, 4),
            "information_ratio": round(ir, 2) if ir is not None else None,
            "hhi": hhi,
            "n_assets": n_assets,
            "trading_days": n,
        }
        result[label] = entry

    return result


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 4: GENERATE DASHBOARD_LATEST.JSON (consolidated model + real)
# ═══════════════════════════════════════════════════════════════════════════════


def _build_model_section() -> dict:
    """Build the 'model' section of dashboard_latest.json."""
    latest_summary = read_json_safe(resolve_source(LATEST_RUN_SUMMARY_JSON))
    optimized = read_json_safe(resolve_source(OPTIMIZED_RECOMMENDATION_JSON))

    bp = latest_summary.get("best_portfolio_details", {})
    comparison = optimized.get("comparison", {})
    holdings = comparison.get("holdings", {})
    ideal = comparison.get("ideal", {})
    optimal = comparison.get("optimal", {})
    momentum_val = bp.get("momentum_valuation", {})

    # Extract model portfolio composition
    model_weights_dict = optimal.get("weights", {}) or ideal.get("weights", {})
    model_stocks = list(model_weights_dict.keys())

    # Returns
    expected_return_hold = safe_float(holdings.get("expected_return_pct"), 0.0)
    expected_return_gross = safe_float(ideal.get("expected_return_pct"), 0.0)
    historical_return = safe_float(
        ideal.get("historical_return_pct"),
        safe_float(bp.get("expected_return_annual_pct"), 0.0),
    )
    expected_volatility = safe_float(bp.get("expected_volatility_annual_pct"), 0.0)

    # Clamp runaway expected returns coming from outlier target prices (e.g., faulty targetMeanPrice)
    MAX_EXPECTED_RETURN_PCT = 200.0  # cap to +200% to avoid 10x+ artifacts
    def clamp_pct(val: float) -> float:
        if val > MAX_EXPECTED_RETURN_PCT:
            logger.warning(
                f"  Model expected return capped: {val:.2f}% → {MAX_EXPECTED_RETURN_PCT:.2f}%"
            )
            return MAX_EXPECTED_RETURN_PCT
        if val < -MAX_EXPECTED_RETURN_PCT:
            logger.warning(
                f"  Model expected return capped: {val:.2f}% → {-MAX_EXPECTED_RETURN_PCT:.2f}%"
            )
            return -MAX_EXPECTED_RETURN_PCT
        return val

    expected_return_gross = clamp_pct(expected_return_gross)
    expected_return_hold = clamp_pct(expected_return_hold)
    historical_return = clamp_pct(historical_return)

    # Sharpe — use the value from A3 optimization (computed consistently with
    # historical returns + volatility).  Recomputing here with target-price
    # returns (ideal.expected_return_pct ≈ 11 %) against historical volatility
    # (≈ 20 %) always yields ≈ 0 and is misleading.
    risk_free = 14.75  # SELIC annual %
    sharpe = bp.get("sharpe_forward", bp.get("sharpe_ratio"))

    # Decision
    # ─────────────────────────────────────────────────────────────────────────
    # net_return     = model gross expected return  −  one-time transition cost
    # excess_return  = net_return  −  current holdings expected return (hold_12m)
    #   > 0  →  model beats current holdings  →  REBALANCE
    #   < 0  →  current holdings beat model   →  HOLD
    # NOTE: excess_return is excess over the *current portfolio*, NOT over
    # any external market index.  Do not label it "vs benchmark" in the UI.
    # ─────────────────────────────────────────────────────────────────────────
    cost_pct = safe_float(optimal.get("transition_cost_pct"), 0.0)
    net_return = expected_return_gross - cost_pct
    excess_return = net_return - expected_return_hold
    threshold = safe_float(optimized.get("min_threshold_pct"), 0.5)
    decision = "REBALANCE" if excess_return > threshold else "HOLD"

    net_return = clamp_pct(net_return)
    excess_return = clamp_pct(excess_return)

    # Additional Risk Metrics (Liquidity and Correlation)
    financials = _load_financials()
    weighted_metrics = _calculate_weighted_metrics(model_weights_dict, financials)
    avg_internal_corr = _calculate_avg_internal_corr(model_stocks)

    return {
        "meta": {
            "run_id": latest_summary.get("last_updated_run_id", ""),
            "timestamp": latest_summary.get("last_updated_timestamp", ""),
        },
        "returns": {
            # hold_12m    : expected return of the *current* portfolio (target-price method)
            # gross_12m   : expected return of the *model* portfolio (before transition cost)
            # net_12m     : gross_12m  −  transition_cost_pct  (what you'd actually earn)
            # excess_net_12m: net_12m  −  hold_12m  (positive = model wins)
            "hold_12m": expected_return_hold,
            "gross_12m": expected_return_gross,
            "net_12m": net_return,
            "historical_annual": historical_return,
            "excess_net_12m": excess_return,
        },
        "risk": {
            "volatility_annual": expected_volatility,
            "risk_free_annual": risk_free,
            "sharpe": sharpe,
            "sharpe_source": "optimization",
            "hhi": bp.get("concentration_risk", {}).get("hhi"),
            "top5": bp.get("concentration_risk", {}).get("top_5_holdings_pct"),
            "liquidity_avg": weighted_metrics.get("liquidity"),
            "avg_internal_corr": avg_internal_corr,
        },
        "decision": {
            "verdict": decision,
            "threshold_pct": threshold,
            "intensity": safe_float(optimal.get("blend_ratio"), 0.0) * 100,
        },
        "valuation": {
            "portfolio_pe": momentum_val.get("portfolio_forward_pe"),
            "benchmark_pe": momentum_val.get("benchmark_forward_pe"),
            "dividend_yield": momentum_val.get("portfolio_dividend_yield"),
            "momentum_signal": momentum_val.get("portfolio_momentum"),
        },
        "composition": {
            "sector_exposure": bp.get("sector_exposure_list", []),
        },
    }


def _build_real_section(real_metrics: dict, risk_windows: Optional[dict] = None,
                        monthly_returns: Optional[dict] = None) -> dict:
    """Build the 'real' section of dashboard_latest.json (Mudança 3).

    Uses TWR metrics computed from the real daily series instead of
    model diagnostics from A4.
    """
    # Read portfolio history CSV for date range
    history_start = None
    history_end = None
    trading_days = 0
    if PORTFOLIO_HISTORY_CSV.exists():
        try:
            hist_df = pd.read_csv(PORTFOLIO_HISTORY_CSV, usecols=["date"])
            if not hist_df.empty:
                unique_dates = hist_df["date"].dropna().unique()
                unique_dates.sort()
                history_start = str(unique_dates[0]) if len(unique_dates) > 0 else None
                history_end = str(unique_dates[-1]) if len(unique_dates) > 0 else None
                trading_days = len(unique_dates)
        except Exception as e:
            logger.warning(f"  Could not read portfolio_history.csv: {e}")

    # Compute coverage: tracked portfolio value vs ledger total
    coverage_pct = None
    ledger_data = read_json_safe(resolve_source(LEDGER_POSITIONS_JSON))
    total_ledger_market = safe_float(ledger_data.get("total_current_market"), 0.0)
    total_ledger_invested = safe_float(ledger_data.get("total_invested_cash"), 0.0)

    if PORTFOLIO_HISTORY_CSV.exists() and total_ledger_market > 0:
        try:
            hist_df = pd.read_csv(PORTFOLIO_HISTORY_CSV)
            if not hist_df.empty:
                last_date = hist_df["date"].max()
                last_day = hist_df[hist_df["date"] == last_date]
                tracked_value = last_day["market_value"].iloc[0] if not last_day.empty else 0
                coverage_pct = round((tracked_value / total_ledger_market) * 100, 1)
        except Exception:
            pass

    # Snapshot from ledger_positions.json
    n_positions = len(ledger_data.get("positions", []))
    total_pnl = safe_float(ledger_data.get("total_unrealized_pnl"), 0.0)
    simple_roi = (total_pnl / total_ledger_invested * 100) if total_ledger_invested > 0 else 0.0

    # Additional metrics (P/E, Liquidity, Correlation)
    financials = _load_financials()
    real_weights = {}
    real_tickers = []
    positions = ledger_data.get("positions", [])
    for pos in positions:
        qty = safe_float(pos.get("net_qty"), 0.0)
        price = safe_float(pos.get("current_price"), 0.0)
        mv = qty * price
        if mv > 0:
            sym = pos.get("resolved_symbol", pos.get("symbol", ""))
            real_weights[sym] = mv / total_ledger_market
            real_tickers.append(sym)

    weighted_metrics = _calculate_weighted_metrics(real_weights, financials)
    avg_internal_corr = _calculate_avg_internal_corr(real_tickers)

    # Build sector map for REAL portfolio concentration
    sector_map = {}
    try:
        import csv
        with open(TICKERS_FILE, encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                ticker = row.get("Ticker", "").strip()
                sector_map[ticker.replace('.SA', '')] = row.get("Sector", "Outros")
    except Exception as e:
        logger.warning(f"Failed to load tickers for sector map: {e}")

    # Structure from ledger_positions.json — REAL portfolio concentration
    structure = {}
    positions = ledger_data.get("positions", [])
    if positions and total_ledger_market > 0:
        weights = []
        sector_weights = {}
        for pos in positions:
            qty = safe_float(pos.get("net_qty"), 0.0)
            price = safe_float(pos.get("current_price"), 0.0)
            mv = qty * price
            if mv > 0:
                w = mv / total_ledger_market
                weights.append(w)
                sym = pos.get("resolved_symbol", pos.get("symbol", "")).replace(".SA", "")
                sec = sector_map.get(sym, "Outros")
                sector_weights[sec] = sector_weights.get(sec, 0.0) + w

        weights_sorted = sorted(weights, reverse=True)
        
        sector_list = [{"sector": s, "pct": round(w, 4)} for s, w in sector_weights.items()]
        sector_list.sort(key=lambda x: x["pct"], reverse=True)
        
        structure = {
            "hhi": round(sum(w ** 2 for w in weights), 4),
            "top3": round(sum(weights_sorted[:3]), 4) if len(weights_sorted) >= 3 else round(sum(weights_sorted), 4),
            "top5": round(sum(weights_sorted[:5]), 4) if len(weights_sorted) >= 5 else round(sum(weights_sorted), 4),
            "n_assets": len(weights),
            "sector_exposure": sector_list
        }

    real: Dict[str, Any] = {
        "meta": {
            "history_start": history_start,
            "history_end": history_end,
            "trading_days": trading_days,
            "coverage_pct": coverage_pct,
            "annualize_safe": real_metrics.get("annualize_safe", False),
            "source": "portfolio_history.csv + ledger.csv",
        },
        "snapshot": {
            "total_market": round(total_ledger_market, 2),
            "total_invested": round(total_ledger_invested, 2),
            "unrealized_pnl": round(total_pnl, 2),
            "simple_roi_pct": round(simple_roi, 2),
            "n_positions": n_positions,
        },
        "twr": real_metrics.get("twr", {}),
        "benchmark": real_metrics.get("benchmark", {}),
        "cdi": real_metrics.get("cdi", {}),
        "alpha": real_metrics.get("alpha", {}),
        "relative": real_metrics.get("relative", {}),
        "structure": structure,
        "valuation": {
           "portfolio_pe": weighted_metrics.get("pe"),
        },
        "risk": {
            "liquidity_avg": weighted_metrics.get("liquidity"),
            "avg_internal_corr": avg_internal_corr,
        },
        "risk_windows": risk_windows or {},
        "performance": real_metrics.get("performance", {}),
        "monthly_returns": monthly_returns or {},
    }

    return real


def publish_dashboard_latest(real_metrics: dict, risk_windows: Optional[dict] = None,
                             monthly_returns: Optional[dict] = None) -> None:
    """Generate dashboard_latest.json consolidating model and real portfolio views.

    Replaces the former separate mis_model_latest.json and mis_real_latest.json.
    The 'real' section now uses TWR metrics computed from portfolio_real_daily.csv.
    """
    logger.info("Step 4c: Generating dashboard_latest.json")

    dashboard = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "model": _build_model_section(),
        "real": _build_real_section(real_metrics, risk_windows, monthly_returns),
    }

    write_json(DASHBOARD_LATEST_JSON, dashboard)
    ensure_symlink(DASHBOARD_LATEST_JSON, DST)

    # Symlink history CSVs for frontend access
    ensure_symlink(PORTFOLIO_RESULTS_CSV, DST, "mis_model_history.csv")
    ensure_symlink(DIAGNOSTICS_HISTORY_CSV, DST, "mis_real_history.csv")
    ensure_symlink(ASSET_ATTRIBUTION_CSV, DST, "mis_real_attribution.csv")


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 5: GENERATE PROCESSED_NOTES.JSON COPY
# ═══════════════════════════════════════════════════════════════════════════════


def publish_processed_notes() -> None:
    """Symlink processed_notes.json if it exists in data/."""
    logger.info("Step 5: Linking processed_notes.json")
    src = SRC / "processed_notes.json"
    if src.exists():
        ensure_symlink(src, DST)
    else:
        # May still be in html/data/ from B1 (transition)
        dst = DST / "processed_notes.json"
        if dst.exists():
            logger.info("  processed_notes.json already in html/data/")
        else:
            logger.warning("  processed_notes.json not found")


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 6: SYMLINK PROGRESS FILES
# ═══════════════════════════════════════════════════════════════════════════════


def publish_progress_symlinks() -> None:
    """Ensure progress JSONs in data/ are symlinked into html/data/.

    Progress files are written live by engines during execution.
    If the canonical file in data/ doesn't exist yet, create an empty
    placeholder so the symlink target is valid.
    """
    logger.info("Step 6: Symlinking progress files")
    for name in PROGRESS_FILES:
        canonical = PROGRESS_DIR / name
        # If progress file only exists in html/data/ (transition), move it
        dst = DST / name
        if not canonical.exists() and dst.exists() and not dst.is_symlink():
            dst.rename(canonical)
            logger.info(f"  Migrated {name} → data/")
        # Create empty placeholder if needed
        if not canonical.exists():
            canonical.parent.mkdir(parents=True, exist_ok=True)
            canonical.write_text("{}", encoding="utf-8")
            logger.info(f"  Created empty {name}")
        ensure_symlink(canonical, DST)


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════


def publish_correlation_heatmap(window_days: int = 252) -> None:
    """Step 7: Compute correlation matrix for current holdings + model tickers.

    Reads tickers from optimized_recommendation.json (holdings + optimal
    weights), loads the last `window_days` of daily closes from StockDataDB,
    and writes correlation_model_portfolio.json to html/data/.

    Ticker ordering in the output:
        [holdings-only] + [in-both] + [model-only]

    so that a heatmap shows the two portfolios as distinct visual blocks.
    """
    logger.info("Step 7: Generating correlation heatmap (holdings vs model)")

    out_path = DST / "correlation_model_portfolio.json"

    # --- Load tickers from recommendation ---
    rec = read_json_safe(resolve_source(OPTIMIZED_RECOMMENDATION_JSON))
    if not rec:
        logger.warning("  optimized_recommendation.json not found — skipping correlation")
        return

    holdings_tickers = set(rec.get("comparison", {}).get("holdings", {}).get("weights", {}).keys())
    model_tickers    = set(rec.get("comparison", {}).get("optimal",  {}).get("weights", {}).keys())
    all_tickers      = sorted(holdings_tickers | model_tickers)

    if not all_tickers:
        logger.warning("  No tickers found in recommendation — skipping correlation")
        return

    logger.info(f"  Holdings: {sorted(holdings_tickers)}")
    logger.info(f"  Model:    {sorted(model_tickers)}")

    # --- Load prices from StockDataDB ---
    if not STOCK_DATA_DB.exists():
        logger.warning(f"  {STOCK_DATA_DB.name} not found — skipping correlation")
        return

    try:
        db = pd.read_csv(STOCK_DATA_DB, parse_dates=["Date"])
        db = db[db["Stock"].isin(all_tickers)][["Date", "Stock", "Close"]].dropna()
        pivot = (
            db.pivot_table(index="Date", columns="Stock", values="Close")
            .sort_index()
            .tail(window_days)
        )
        missing = [t for t in all_tickers if t not in pivot.columns]
        if missing:
            logger.warning(f"  Tickers missing from StockDataDB: {missing}")
            all_tickers = [t for t in all_tickers if t in pivot.columns]
            holdings_tickers -= set(missing)
            model_tickers    -= set(missing)

        returns = pivot[all_tickers].pct_change().dropna()
        corr    = returns.corr().round(4)
        date    = pivot.index[-1].strftime("%Y-%m-%d")
        actual_window = len(returns)
        logger.info(f"  Window: {pivot.index[0].date()} → {date} ({actual_window} return days)")
    except Exception as e:
        logger.error(f"  Failed to compute correlations: {e}")
        return

    # --- Group labels and display order ---
    groups: Dict[str, str] = {}
    for t in all_tickers:
        in_h = t in holdings_tickers
        in_m = t in model_tickers
        groups[t] = "both" if (in_h and in_m) else ("holdings" if in_h else "model")

    order: List[str] = (
        [t for t in sorted(holdings_tickers) if groups[t] == "holdings"] +
        [t for t in sorted(all_tickers)      if groups[t] == "both"]     +
        [t for t in sorted(model_tickers)    if groups[t] == "model"]
    )

    matrix: List[List[Optional[float]]] = []
    for r in order:
        row: List[Optional[float]] = []
        for c in order:
            try:
                v = float(corr.loc[r, c])
                row.append(None if not math.isfinite(v) else round(v, 4))
            except (KeyError, TypeError):
                row.append(None)
        matrix.append(row)

    payload = {
        "date":        date,
        "window_days": actual_window,
        "tickers":     order,
        "groups":      groups,
        "matrix":      matrix,
    }

    write_json(out_path, payload)
    logger.info(f"  Saved {out_path.name} ({len(order)}×{len(order)} matrix)")


def publish_history_enriched() -> None:
    """Step 8: Generate portfolio_history_enriched.json for the History page.

    Merges data from:
      - portfolio_results_db.csv       (A3 engine: backtest metrics)
      - optimized_portfolio_history.jsonl  (C engine: forward-looking metrics)
      - latest_run_summary.json        (momentum for the latest run)

    Output: html/data/portfolio_history_enriched.json
    """
    logger.info("Step 8: Generating portfolio_history_enriched.json")

    out_path = DST / "portfolio_history_enriched.json"

    # --- Load A3 results (CSV) ---
    csv_path = PORTFOLIO_RESULTS_CSV
    if not csv_path.exists():
        logger.warning("  portfolio_results_db.csv not found — skipping")
        return

    try:
        a3_df = pd.read_csv(csv_path)
    except Exception as e:
        logger.error(f"  Failed to read portfolio_results_db.csv: {e}")
        return

    # --- Load C results (JSONL) ---
    c_entries = []
    if OPTIMIZED_HISTORY_JSONL.exists():
        try:
            with open(OPTIMIZED_HISTORY_JSONL, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line:
                        c_entries.append(json.loads(line))
        except Exception as e:
            logger.warning(f"  Failed to read JSONL: {e}")

    # Parse C timestamps for proximity matching
    for entry in c_entries:
        try:
            entry["_ts"] = datetime.strptime(entry["timestamp"], "%Y-%m-%d %H:%M:%S")
        except Exception:
            entry["_ts"] = None

    # --- Load momentum from latest_run_summary.json ---
    latest_summary = read_json_safe(LATEST_RUN_SUMMARY_JSON)
    latest_run_id = latest_summary.get("last_updated_run_id", "")
    latest_momentum = None
    bp = latest_summary.get("best_portfolio_details", {})
    mv = bp.get("momentum_valuation", {})
    if mv:
        latest_momentum = mv.get("portfolio_momentum")

    # --- Build enriched entries ---
    enriched = []

    for _, row in a3_df.iterrows():
        run_id = str(row.get("run_id", ""))
        timestamp_str = str(row.get("timestamp", ""))

        # Parse stocks
        stocks_raw = str(row.get("stocks", ""))
        stocks = [
            s.strip()
            for s in stocks_raw.replace("'", "").replace("[", "").replace("]", "").split(",")
            if s.strip()
        ]

        # Parse weights
        weights_raw = str(row.get("weights", ""))
        weights = []
        for w in weights_raw.replace("[", "").replace("]", "").split(","):
            try:
                weights.append(float(w.strip()))
            except (ValueError, TypeError):
                pass

        entry: Dict[str, Any] = {
            "run_id": run_id,
            "timestamp": timestamp_str,
            "n_assets": len(stocks),
            "stocks": stocks,
            "weights": weights,
            # A3 backward-looking
            "sharpe_forward": safe_float(row.get("sharpe_forward"), None),
            "ret_hist_12m": safe_float(row.get("expected_return_annual_pct"), None),
            "vol_12m": safe_float(row.get("expected_volatility_annual_pct"), None),
            # C forward-looking (filled below via timestamp match)
            "ret_proj_12m": None,
            "score": None,
            "momentum": None,
            # Detail for expandable panel
            "decision": None,
            "transition_cost_pct": None,
            "holdings_return_pct": None,
            "excess_return_pct": None,
        }

        # --- Match with C engine entry by timestamp proximity (±30 min) ---
        if timestamp_str and c_entries:
            try:
                a3_ts = datetime.strptime(timestamp_str, "%Y-%m-%d %H:%M:%S")
                best_match = None
                best_delta = timedelta(minutes=30)

                for c in c_entries:
                    if c.get("_ts") is None:
                        continue
                    delta = abs(c["_ts"] - a3_ts)
                    if delta < best_delta:
                        best_delta = delta
                        best_match = c

                if best_match:
                    entry["ret_proj_12m"] = best_match.get("ideal_return_pct")
                    entry["score"] = best_match.get("ideal_score")
                    entry["decision"] = best_match.get("decision")
                    entry["transition_cost_pct"] = best_match.get("transition_cost_pct")
                    entry["holdings_return_pct"] = best_match.get("holdings_return_pct")
                    entry["excess_return_pct"] = best_match.get("excess_return_pct")
            except Exception:
                pass

        # Momentum: only available for latest run (not persisted per-run)
        if run_id == latest_run_id and latest_momentum is not None:
            entry["momentum"] = latest_momentum

        enriched.append(entry)

    # Sort by run_id descending (newest first)
    enriched.sort(key=lambda x: x.get("run_id", ""), reverse=True)

    write_json(out_path, enriched)
    logger.info(f"  Saved portfolio_history_enriched.json ({len(enriched)} runs)")


def main() -> int:
    start_time = datetime.now()
    logger.info(f"D_Publish.py v{D_PUBLISH_VERSION} — Starting frontend asset publication")
    logger.info(f"Source: {SRC}")
    logger.info(f"Target: {DST}")

    DST.mkdir(parents=True, exist_ok=True)

    try:
        # Step 0: Generate derived snapshot JSONs from history CSVs
        publish_derived_snapshots()

        # Step 1: Symlink canonical files
        publish_symlink_files()

        # Step 2: Generate scored_targets.json
        target_map = publish_scored_targets()

        # Step 3: Generate pipeline_latest.json
        publish_pipeline_latest(target_map)

        # Step 4a: Generate portfolio_real_daily.csv (Mudança 1)
        daily_df = _build_real_daily_series()

        # Step 4b: Compute real TWR metrics (Mudança 2)
        real_metrics = _compute_real_metrics(daily_df)

        # Step 4b2: Compute risk windows (TE, IR, HHI per time window)
        hist_df = pd.read_csv(PORTFOLIO_HISTORY_CSV) if PORTFOLIO_HISTORY_CSV.exists() else pd.DataFrame()
        risk_windows = _compute_risk_windows(daily_df, hist_df)


        # Step 4b4: Compute TWR monthly returns (método da cota)
        logger.info("Step 4b4: Computing TWR monthly returns (quota method)")
        monthly_returns = compute_monthly_twr_from_daily(daily_df)
        if monthly_returns:
            logger.info(
                f"  TWR monthly: {len(monthly_returns.get('meses', []))} months, "
                f"total={monthly_returns.get('twr_total', 0):+.4f}"
            )

        # Step 4c: Generate consolidated dashboard JSON (Mudança 3)
        publish_dashboard_latest(real_metrics, risk_windows, monthly_returns)

        # Step 5: Processed notes
        publish_processed_notes()

        # Step 6: Progress file symlinks
        publish_progress_symlinks()

        # Step 7: Correlation heatmap JSON (portfolio holdings vs model tickers)
        publish_correlation_heatmap()

        # Step 8: Enriched history JSON (A3 + C merged for frontend)
        publish_history_enriched()

        elapsed = (datetime.now() - start_time).total_seconds()
        logger.info(f"D_Publish.py completed in {elapsed:.1f}s")
        return 0

    except Exception as e:
        logger.critical(f"D_Publish.py failed: {e}", exc_info=True)
        return 1


if __name__ == "__main__":
    sys.exit(main())



